// <auto-generated />
using System;
using BodyRocky.Back.WebApi.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BodyRocky.Back.WebApi.Migrations
{
    [DbContext(typeof(BodyRockyDbContext))]
    [Migration("20221002190343_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Address", b =>
                {
                    b.Property<Guid>("AddressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddressFromDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AddressToDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("AddressID");

                    b.ToTable("Address", (string)null);
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Basket", b =>
                {
                    b.Property<Guid>("BasketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BasketDateAdded")
                        .HasColumnType("datetime2");

                    b.Property<int>("BasketStatusCode")
                        .HasColumnType("int");

                    b.HasKey("BasketID");

                    b.HasIndex("BasketStatusCode");

                    b.ToTable("Basket", (string)null);
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.BasketProduct", b =>
                {
                    b.Property<Guid>("BasketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("BasketId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("BasketProduct");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.BasketStatus", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("BasketStatus", (string)null);
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Brand", b =>
                {
                    b.Property<Guid>("BrandID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrandLogo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrandID");

                    b.ToTable("Brand", (string)null);
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Category", b =>
                {
                    b.Property<Guid>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryID1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.HasKey("CategoryID");

                    b.HasIndex("CategoryID1");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Customer", b =>
                {
                    b.Property<Guid>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customer", (string)null);

                    b.HasData(
                        new
                        {
                            CustomerID = new Guid("719e2599-5766-6251-5611-2c2bf79f45c0"),
                            BirthDate = new DateTime(2022, 3, 2, 4, 10, 12, 941, DateTimeKind.Local).AddTicks(2354),
                            EmailAddress = "Victoria.Bode@gmail.com",
                            FirstName = "Victoria",
                            LastName = "Bode",
                            Password = "62d6347b958103bdc8b148830927f1a6da33289f",
                            PhoneNumber = "1-233-768-9374"
                        },
                        new
                        {
                            CustomerID = new Guid("ed90974e-c8ce-dbbb-1348-ceb389c2e723"),
                            BirthDate = new DateTime(2014, 3, 3, 20, 22, 14, 619, DateTimeKind.Local).AddTicks(6481),
                            EmailAddress = "Juana_Jerde69@gmail.com",
                            FirstName = "Juana",
                            LastName = "Jerde",
                            Password = "82f084127c07b4124b3bfa8af9131d1396512b26",
                            PhoneNumber = "794-781-9387"
                        },
                        new
                        {
                            CustomerID = new Guid("a253cbdb-266b-12e3-1267-3fee72d75e43"),
                            BirthDate = new DateTime(2010, 5, 8, 7, 33, 54, 47, DateTimeKind.Local).AddTicks(6754),
                            EmailAddress = "May.Sipes45@hotmail.com",
                            FirstName = "May",
                            LastName = "Sipes",
                            Password = "47c7033ddf069a2803e561da0890738a1c9df01c",
                            PhoneNumber = "833.994.0512"
                        },
                        new
                        {
                            CustomerID = new Guid("bbc6cffa-a097-9a5a-63a5-6ec941494884"),
                            BirthDate = new DateTime(2020, 2, 8, 0, 6, 35, 789, DateTimeKind.Local).AddTicks(4084),
                            EmailAddress = "Belinda_McDermott18@gmail.com",
                            FirstName = "Belinda",
                            LastName = "McDermott",
                            Password = "ef293838ba0fb5cf834ac126f731f0c4b1dc1fc4",
                            PhoneNumber = "(527) 718-6586 x6471"
                        },
                        new
                        {
                            CustomerID = new Guid("60c6675b-18d3-48e3-1d8e-c51781c0cd91"),
                            BirthDate = new DateTime(2016, 11, 22, 11, 19, 27, 230, DateTimeKind.Local).AddTicks(1034),
                            EmailAddress = "Andy90@gmail.com",
                            FirstName = "Andy",
                            LastName = "Gleason",
                            Password = "0ce29e83c14984e344e989eb0d02afde5c0f5777",
                            PhoneNumber = "345.340.8775"
                        },
                        new
                        {
                            CustomerID = new Guid("62f650d6-3b74-e91e-815a-265cb3178d91"),
                            BirthDate = new DateTime(2018, 12, 31, 7, 36, 32, 370, DateTimeKind.Local).AddTicks(8417),
                            EmailAddress = "Margarita_Crooks@gmail.com",
                            FirstName = "Margarita",
                            LastName = "Crooks",
                            Password = "6f3a7c33122ce7ad25329281f4b17d7a7f5afdee",
                            PhoneNumber = "850-593-4981 x166"
                        },
                        new
                        {
                            CustomerID = new Guid("e09cb287-369d-6874-2203-b3ad09c77532"),
                            BirthDate = new DateTime(2021, 8, 23, 17, 51, 47, 653, DateTimeKind.Local).AddTicks(8886),
                            EmailAddress = "Wendy63@yahoo.com",
                            FirstName = "Wendy",
                            LastName = "Nolan",
                            Password = "ea35b11cd5b098684f6ed9cd21211af2d0de57a7",
                            PhoneNumber = "1-385-276-5111 x785"
                        },
                        new
                        {
                            CustomerID = new Guid("c2d14246-3307-3f14-4d13-dbbb7535e733"),
                            BirthDate = new DateTime(2011, 1, 29, 10, 6, 13, 71, DateTimeKind.Local).AddTicks(3259),
                            EmailAddress = "Dave8@hotmail.com",
                            FirstName = "Dave",
                            LastName = "Treutel",
                            Password = "76691233b22f75d48842c88e961fa3d2655355fd",
                            PhoneNumber = "(984) 273-6101 x00239"
                        },
                        new
                        {
                            CustomerID = new Guid("814dd92f-f340-bc0e-1e93-24b9dc0b845a"),
                            BirthDate = new DateTime(2005, 7, 12, 23, 49, 3, 409, DateTimeKind.Local).AddTicks(281),
                            EmailAddress = "Eula_Zemlak@yahoo.com",
                            FirstName = "Eula",
                            LastName = "Zemlak",
                            Password = "1425fd97c595eb0e6241be848037b293ee2d6f77",
                            PhoneNumber = "(773) 309-1569 x48798"
                        },
                        new
                        {
                            CustomerID = new Guid("a24b9981-cd06-2b26-91ba-95bc452d85d2"),
                            BirthDate = new DateTime(2009, 7, 11, 5, 4, 27, 928, DateTimeKind.Local).AddTicks(8323),
                            EmailAddress = "Holly6@yahoo.com",
                            FirstName = "Holly",
                            LastName = "Bogisich",
                            Password = "56c063c93e0547dff9f12f76efb7e1390a21ad70",
                            PhoneNumber = "1-846-429-9540 x25620"
                        },
                        new
                        {
                            CustomerID = new Guid("1f06f1d4-7331-375e-3352-2a521c9cbd35"),
                            BirthDate = new DateTime(2004, 10, 12, 0, 32, 38, 499, DateTimeKind.Local).AddTicks(5306),
                            EmailAddress = "Roderick_OKeefe@hotmail.com",
                            FirstName = "Roderick",
                            LastName = "O'Keefe",
                            Password = "6c5aca8a3a842ce2681ad637c55da0afe179c097",
                            PhoneNumber = "1-216-323-6087 x69980"
                        },
                        new
                        {
                            CustomerID = new Guid("a10da5b1-7317-2d07-882b-34444d5f1fb3"),
                            BirthDate = new DateTime(2004, 11, 22, 1, 7, 48, 617, DateTimeKind.Local).AddTicks(7436),
                            EmailAddress = "Clyde38@yahoo.com",
                            FirstName = "Clyde",
                            LastName = "Bayer",
                            Password = "3c5700d80fb50fd186394ee2182d72109fd25bb9",
                            PhoneNumber = "1-862-530-8172"
                        },
                        new
                        {
                            CustomerID = new Guid("32d9510b-b32d-07fc-fa84-27fd0155ccfc"),
                            BirthDate = new DateTime(2021, 2, 28, 9, 18, 38, 78, DateTimeKind.Local).AddTicks(8919),
                            EmailAddress = "Deborah_Smitham@gmail.com",
                            FirstName = "Deborah",
                            LastName = "Smitham",
                            Password = "f47cc13323b79eee2793ded70cd2cdbf093d7a40",
                            PhoneNumber = "698.537.7004 x11011"
                        },
                        new
                        {
                            CustomerID = new Guid("a2d96232-67c2-af6c-fbe2-6dc0d1371b75"),
                            BirthDate = new DateTime(2010, 4, 25, 2, 2, 36, 504, DateTimeKind.Local).AddTicks(9869),
                            EmailAddress = "Ray72@hotmail.com",
                            FirstName = "Ray",
                            LastName = "Zemlak",
                            Password = "66f17cc33c1c2d8053acad0ed2a1a88ed4b6a120",
                            PhoneNumber = "397-894-9581 x8438"
                        },
                        new
                        {
                            CustomerID = new Guid("59392b49-7be3-2f41-9ecc-1287d3edd780"),
                            BirthDate = new DateTime(2020, 6, 20, 6, 22, 51, 429, DateTimeKind.Local).AddTicks(217),
                            EmailAddress = "Sadie43@yahoo.com",
                            FirstName = "Sadie",
                            LastName = "Blanda",
                            Password = "d6be4b43970dd75d7aeb9aa90cf38abce5920c05",
                            PhoneNumber = "(847) 508-4299"
                        },
                        new
                        {
                            CustomerID = new Guid("307814ac-7380-1e7b-ea0e-c4f38263aaa3"),
                            BirthDate = new DateTime(2021, 3, 1, 16, 30, 58, 472, DateTimeKind.Local).AddTicks(1293),
                            EmailAddress = "Betsy.Grimes@yahoo.com",
                            FirstName = "Betsy",
                            LastName = "Grimes",
                            Password = "5117f17e6a58656fe30ddf4294251a3165e2ef57",
                            PhoneNumber = "1-571-222-0603"
                        },
                        new
                        {
                            CustomerID = new Guid("a0d87812-1b4e-0370-6f9f-1d78724c811a"),
                            BirthDate = new DateTime(2012, 10, 29, 12, 26, 49, 496, DateTimeKind.Local).AddTicks(4805),
                            EmailAddress = "Ed.Kovacek@gmail.com",
                            FirstName = "Ed",
                            LastName = "Kovacek",
                            Password = "cb50e321b36bfe9a8b34250ae2df76cb39ce8108",
                            PhoneNumber = "244-967-6188 x207"
                        },
                        new
                        {
                            CustomerID = new Guid("0afaf97c-0003-797c-fcbc-a416ed8444c4"),
                            BirthDate = new DateTime(2009, 11, 8, 15, 24, 11, 174, DateTimeKind.Local).AddTicks(5858),
                            EmailAddress = "Stacey88@hotmail.com",
                            FirstName = "Stacey",
                            LastName = "Baumbach",
                            Password = "70f946915560c464452885d78872ddec87f3cf9e",
                            PhoneNumber = "(297) 283-9673 x51018"
                        },
                        new
                        {
                            CustomerID = new Guid("d1be9f91-7f34-1594-e670-c0e7c1fa4b89"),
                            BirthDate = new DateTime(2022, 8, 14, 1, 54, 47, 986, DateTimeKind.Local).AddTicks(189),
                            EmailAddress = "Kent.DuBuque@yahoo.com",
                            FirstName = "Kent",
                            LastName = "DuBuque",
                            Password = "315522af26b12cf25398b9be7dfc8fe8bc48fa3d",
                            PhoneNumber = "(584) 508-7404 x133"
                        },
                        new
                        {
                            CustomerID = new Guid("57edce97-fb39-6ca8-98d7-ca25e90d3d96"),
                            BirthDate = new DateTime(2014, 5, 14, 5, 2, 17, 165, DateTimeKind.Local).AddTicks(9068),
                            EmailAddress = "Edmond_Ledner42@yahoo.com",
                            FirstName = "Edmond",
                            LastName = "Ledner",
                            Password = "fb425d63c6b5a8042a0b1897053bde881178cbcc",
                            PhoneNumber = "430-947-2002 x6161"
                        },
                        new
                        {
                            CustomerID = new Guid("81ed7a05-bec6-a866-c17a-93440e772bd0"),
                            BirthDate = new DateTime(2008, 1, 23, 9, 47, 25, 287, DateTimeKind.Local).AddTicks(9318),
                            EmailAddress = "Hope76@yahoo.com",
                            FirstName = "Hope",
                            LastName = "Grady",
                            Password = "a7bbfdf9ba54fa8ec508912b46f970c672b8257a",
                            PhoneNumber = "1-210-595-8707"
                        },
                        new
                        {
                            CustomerID = new Guid("8ce95249-f837-47b2-db12-5ee799da4834"),
                            BirthDate = new DateTime(2018, 10, 15, 0, 31, 56, 82, DateTimeKind.Local).AddTicks(3889),
                            EmailAddress = "Dianna.Adams77@yahoo.com",
                            FirstName = "Dianna",
                            LastName = "Adams",
                            Password = "5415a2f37984fbb16296d52f3c4f810b363a4b21",
                            PhoneNumber = "540.959.9177"
                        },
                        new
                        {
                            CustomerID = new Guid("e29fd9b4-1dbb-ea35-9114-9d4f2473ae1e"),
                            BirthDate = new DateTime(2005, 5, 19, 1, 59, 50, 693, DateTimeKind.Local).AddTicks(5868),
                            EmailAddress = "Christina_Effertz@yahoo.com",
                            FirstName = "Christina",
                            LastName = "Effertz",
                            Password = "15e6f4901e00fe458eadfbc70c73bc382b4f8e83",
                            PhoneNumber = "228-305-9654 x36810"
                        },
                        new
                        {
                            CustomerID = new Guid("363ac938-b99a-942d-c13b-7629eb28ceb9"),
                            BirthDate = new DateTime(2015, 1, 19, 22, 55, 59, 987, DateTimeKind.Local).AddTicks(6457),
                            EmailAddress = "Darrin.Schroeder@yahoo.com",
                            FirstName = "Darrin",
                            LastName = "Schroeder",
                            Password = "a057f2336048446e7270214cac247e2e1aeffef0",
                            PhoneNumber = "297-688-4750"
                        },
                        new
                        {
                            CustomerID = new Guid("3bd619de-e507-ae53-9a9c-198449289a85"),
                            BirthDate = new DateTime(2007, 11, 30, 9, 4, 17, 319, DateTimeKind.Local).AddTicks(3200),
                            EmailAddress = "Sheryl45@gmail.com",
                            FirstName = "Sheryl",
                            LastName = "Prosacco",
                            Password = "169a23dfc9a609915db123d33dfa4c17cf4441f5",
                            PhoneNumber = "372.783.7284"
                        },
                        new
                        {
                            CustomerID = new Guid("d85439bd-7831-d176-b351-d29e1a9fdf21"),
                            BirthDate = new DateTime(2009, 11, 21, 1, 52, 50, 241, DateTimeKind.Local).AddTicks(9789),
                            EmailAddress = "Grady75@hotmail.com",
                            FirstName = "Grady",
                            LastName = "Jenkins",
                            Password = "385f28305ca754e179b42ef68c009c3a1e62446f",
                            PhoneNumber = "251.897.6220"
                        },
                        new
                        {
                            CustomerID = new Guid("ae149335-880b-ba23-8a17-8eddc2d3f5b7"),
                            BirthDate = new DateTime(2022, 3, 6, 15, 32, 47, 658, DateTimeKind.Local).AddTicks(7335),
                            EmailAddress = "Rudy27@yahoo.com",
                            FirstName = "Rudy",
                            LastName = "Jacobson",
                            Password = "6690c0d6a189b3ab17e59b140a3a0f74bbc74ab2",
                            PhoneNumber = "1-649-711-7095"
                        },
                        new
                        {
                            CustomerID = new Guid("fc4e5d28-531f-60bd-f873-8c42513981a2"),
                            BirthDate = new DateTime(2008, 11, 3, 12, 8, 45, 944, DateTimeKind.Local).AddTicks(3358),
                            EmailAddress = "Terry.Berge@gmail.com",
                            FirstName = "Terry",
                            LastName = "Berge",
                            Password = "fd685309c9964305a418fb00a0b88922b4178af5",
                            PhoneNumber = "(932) 419-9440"
                        },
                        new
                        {
                            CustomerID = new Guid("4a761bd5-bce0-83f5-405a-64d7d95f9e43"),
                            BirthDate = new DateTime(2016, 7, 18, 19, 53, 49, 320, DateTimeKind.Local).AddTicks(2763),
                            EmailAddress = "Jesus_Kris59@yahoo.com",
                            FirstName = "Jesus",
                            LastName = "Kris",
                            Password = "329ce543815365c7bdf422bf1fea46ee1c287517",
                            PhoneNumber = "(288) 517-8815"
                        },
                        new
                        {
                            CustomerID = new Guid("c5bf508a-8b1c-dc67-0a7c-592dc5fa9cf6"),
                            BirthDate = new DateTime(2007, 6, 18, 1, 18, 25, 164, DateTimeKind.Local).AddTicks(147),
                            EmailAddress = "Lorena.Osinski99@gmail.com",
                            FirstName = "Lorena",
                            LastName = "Osinski",
                            Password = "f82aa3d51621f7203ac5b899f5ea98354fe0c2d9",
                            PhoneNumber = "966.238.1749"
                        },
                        new
                        {
                            CustomerID = new Guid("77c666c3-87b2-ee8c-c1da-c11c15a92fed"),
                            BirthDate = new DateTime(2020, 12, 17, 17, 7, 49, 374, DateTimeKind.Local).AddTicks(6418),
                            EmailAddress = "Janie_Collins@yahoo.com",
                            FirstName = "Janie",
                            LastName = "Collins",
                            Password = "ed5b3cdfcf9db1bfeb7bf16bdfa854557e2b5382",
                            PhoneNumber = "1-817-753-9794"
                        },
                        new
                        {
                            CustomerID = new Guid("1478da06-d81c-e683-1d19-bc5f4ae91de7"),
                            BirthDate = new DateTime(2008, 2, 11, 4, 11, 36, 112, DateTimeKind.Local).AddTicks(6640),
                            EmailAddress = "Jeremy_Baumbach@hotmail.com",
                            FirstName = "Jeremy",
                            LastName = "Baumbach",
                            Password = "83083ac12f6b047feda8af27c6ffe9d118b69461",
                            PhoneNumber = "1-618-994-2223 x95552"
                        },
                        new
                        {
                            CustomerID = new Guid("e34e1fe4-006c-4566-2fba-16222d46f98b"),
                            BirthDate = new DateTime(2009, 6, 7, 2, 9, 27, 16, DateTimeKind.Local).AddTicks(5924),
                            EmailAddress = "Essie_Hintz18@hotmail.com",
                            FirstName = "Essie",
                            LastName = "Hintz",
                            Password = "9a51179c702c9ae4d89e757e1f7e4b5634eefecf",
                            PhoneNumber = "492-481-9243 x61405"
                        },
                        new
                        {
                            CustomerID = new Guid("43794dbb-45d8-c913-8ee2-16be50d66511"),
                            BirthDate = new DateTime(2015, 4, 17, 7, 42, 11, 387, DateTimeKind.Local).AddTicks(2697),
                            EmailAddress = "Leona_Wiegand@yahoo.com",
                            FirstName = "Leona",
                            LastName = "Wiegand",
                            Password = "cba1bc27e0eb22b581f9efd6e1e1f45e220eb81b",
                            PhoneNumber = "933.575.5802 x51283"
                        },
                        new
                        {
                            CustomerID = new Guid("392bc9a7-3d17-313b-0cdd-cf25f866b085"),
                            BirthDate = new DateTime(2008, 3, 21, 11, 11, 35, 197, DateTimeKind.Local).AddTicks(3919),
                            EmailAddress = "Danny.Runte@hotmail.com",
                            FirstName = "Danny",
                            LastName = "Runte",
                            Password = "4f9bbc164bffdc0b09be270e4d34e6b2bcbf3c6d",
                            PhoneNumber = "1-998-883-5445"
                        },
                        new
                        {
                            CustomerID = new Guid("e15e2568-f789-e1b3-009b-9d3fa97d4352"),
                            BirthDate = new DateTime(2021, 8, 3, 1, 18, 24, 231, DateTimeKind.Local).AddTicks(2361),
                            EmailAddress = "Myra42@yahoo.com",
                            FirstName = "Myra",
                            LastName = "Blanda",
                            Password = "788daec3fb491aac36dea926dc74640b47ff2ef2",
                            PhoneNumber = "1-505-377-2272"
                        },
                        new
                        {
                            CustomerID = new Guid("ecae53c4-e059-bccb-65c2-1c911642bf5a"),
                            BirthDate = new DateTime(2012, 3, 25, 2, 18, 16, 179, DateTimeKind.Local).AddTicks(5287),
                            EmailAddress = "Grace_Collier@hotmail.com",
                            FirstName = "Grace",
                            LastName = "Collier",
                            Password = "b1b245eba639b220bc4e8edbd01d79de0ff03063",
                            PhoneNumber = "860-843-7785"
                        },
                        new
                        {
                            CustomerID = new Guid("76378439-999c-54f2-23fd-17b72b45201b"),
                            BirthDate = new DateTime(2006, 8, 3, 23, 50, 23, 209, DateTimeKind.Local).AddTicks(499),
                            EmailAddress = "Merle_Schiller@yahoo.com",
                            FirstName = "Merle",
                            LastName = "Schiller",
                            Password = "6953f70c9bc282f59ee706aadf200898b17c7643",
                            PhoneNumber = "614-391-6773 x6904"
                        },
                        new
                        {
                            CustomerID = new Guid("462ffa58-eb26-aa7f-6010-1d03a996eef7"),
                            BirthDate = new DateTime(2019, 1, 6, 7, 3, 16, 173, DateTimeKind.Local).AddTicks(6102),
                            EmailAddress = "Dana.Dibbert49@yahoo.com",
                            FirstName = "Dana",
                            LastName = "Dibbert",
                            Password = "2279b6485c9c32f2aaf06ff1196aba36eddfc50b",
                            PhoneNumber = "507.279.8623"
                        },
                        new
                        {
                            CustomerID = new Guid("0ab31ab1-6cca-f6c7-b5d2-f3a074287d5c"),
                            BirthDate = new DateTime(2021, 4, 4, 17, 11, 36, 752, DateTimeKind.Local).AddTicks(679),
                            EmailAddress = "Lydia22@gmail.com",
                            FirstName = "Lydia",
                            LastName = "Blick",
                            Password = "fad00bc2685f8293c672c41d268c1ff1e67d1c22",
                            PhoneNumber = "(661) 757-2446 x006"
                        },
                        new
                        {
                            CustomerID = new Guid("fdb3f144-b34c-f907-bc45-6bc06130dabe"),
                            BirthDate = new DateTime(2018, 7, 31, 8, 11, 40, 447, DateTimeKind.Local).AddTicks(8893),
                            EmailAddress = "Cameron52@gmail.com",
                            FirstName = "Cameron",
                            LastName = "Stroman",
                            Password = "e338beddb4fc8d6cd2da4ab080afdbda7f5d2b61",
                            PhoneNumber = "1-220-259-0892"
                        },
                        new
                        {
                            CustomerID = new Guid("0ed92e86-f0e6-40fe-91d6-a5189d87ffc4"),
                            BirthDate = new DateTime(2021, 3, 2, 17, 21, 4, 249, DateTimeKind.Local).AddTicks(9730),
                            EmailAddress = "Ebony34@yahoo.com",
                            FirstName = "Ebony",
                            LastName = "Wisozk",
                            Password = "9c4ed5d078636edb8e216248761ecf0971996d42",
                            PhoneNumber = "(756) 377-7522"
                        },
                        new
                        {
                            CustomerID = new Guid("db9feb41-6c31-6790-3ade-12e27e63471e"),
                            BirthDate = new DateTime(2017, 9, 14, 17, 34, 7, 722, DateTimeKind.Local).AddTicks(2149),
                            EmailAddress = "Mack.Hintz73@yahoo.com",
                            FirstName = "Mack",
                            LastName = "Hintz",
                            Password = "39ce21daebc8aa69b3fdd3dd6d885a4439ce487e",
                            PhoneNumber = "1-906-260-9273 x022"
                        },
                        new
                        {
                            CustomerID = new Guid("68c7ca71-2309-6d2b-831c-eac7c37ab3b6"),
                            BirthDate = new DateTime(2009, 5, 31, 12, 9, 20, 666, DateTimeKind.Local).AddTicks(8420),
                            EmailAddress = "Shane.Mraz@hotmail.com",
                            FirstName = "Shane",
                            LastName = "Mraz",
                            Password = "2bafbe07c9f2c53d80bc0bbdff85095f0bccf583",
                            PhoneNumber = "386-968-2732"
                        },
                        new
                        {
                            CustomerID = new Guid("074a1242-73d9-a485-7df0-f160dd454f1f"),
                            BirthDate = new DateTime(2016, 4, 8, 16, 21, 11, 108, DateTimeKind.Local).AddTicks(3446),
                            EmailAddress = "Norman46@gmail.com",
                            FirstName = "Norman",
                            LastName = "Treutel",
                            Password = "7f9aa8c5cd222ba4eeb4cf42e61875328582e12c",
                            PhoneNumber = "1-616-207-7048"
                        },
                        new
                        {
                            CustomerID = new Guid("433e01bc-d81e-4330-2596-6b876442df57"),
                            BirthDate = new DateTime(2021, 10, 8, 9, 32, 0, 286, DateTimeKind.Local).AddTicks(3475),
                            EmailAddress = "Courtney75@gmail.com",
                            FirstName = "Courtney",
                            LastName = "Dach",
                            Password = "649b2e4c3e91c90a9bac1d2db864c676964db004",
                            PhoneNumber = "1-946-964-5804"
                        },
                        new
                        {
                            CustomerID = new Guid("78d31a0c-36de-4777-a5f2-28b9cfdab52c"),
                            BirthDate = new DateTime(2019, 3, 22, 1, 5, 32, 62, DateTimeKind.Local).AddTicks(7635),
                            EmailAddress = "Lorene_Schaefer39@hotmail.com",
                            FirstName = "Lorene",
                            LastName = "Schaefer",
                            Password = "14f202fef5342358d5617a14a48e5722fdc559d1",
                            PhoneNumber = "1-851-780-6248"
                        },
                        new
                        {
                            CustomerID = new Guid("44ba3c65-046f-b89a-d1c8-f079f6e49262"),
                            BirthDate = new DateTime(2018, 10, 19, 19, 27, 30, 318, DateTimeKind.Local).AddTicks(2555),
                            EmailAddress = "Edmond69@gmail.com",
                            FirstName = "Edmond",
                            LastName = "Murray",
                            Password = "be0692a3a55708223521fc449cb9d9db7243fec3",
                            PhoneNumber = "(212) 949-5218 x253"
                        },
                        new
                        {
                            CustomerID = new Guid("a5e2eecf-bea9-ff40-f1f1-3e8b96e324e7"),
                            BirthDate = new DateTime(2012, 12, 28, 15, 43, 53, 146, DateTimeKind.Local).AddTicks(3849),
                            EmailAddress = "Fred.McKenzie94@hotmail.com",
                            FirstName = "Fred",
                            LastName = "McKenzie",
                            Password = "19c2f25bd6372a8c0c3d397272bca70ae4d364cc",
                            PhoneNumber = "841-520-7118 x5611"
                        },
                        new
                        {
                            CustomerID = new Guid("0fa4e699-8596-c6fe-7ab7-31b5d408d1f6"),
                            BirthDate = new DateTime(2012, 3, 27, 22, 36, 36, 534, DateTimeKind.Local).AddTicks(35),
                            EmailAddress = "Doris.Halvorson54@yahoo.com",
                            FirstName = "Doris",
                            LastName = "Halvorson",
                            Password = "b973e11022a6bcb89a0aead8b4e009b648ce95b8",
                            PhoneNumber = "981-638-4421"
                        },
                        new
                        {
                            CustomerID = new Guid("580784c3-c108-afaf-93f3-2cb9dfc97a85"),
                            BirthDate = new DateTime(2010, 3, 13, 19, 49, 16, 568, DateTimeKind.Local).AddTicks(230),
                            EmailAddress = "Alberto_Kessler@hotmail.com",
                            FirstName = "Alberto",
                            LastName = "Kessler",
                            Password = "16d85bc1fe3b987796607f18b076363c6488a797",
                            PhoneNumber = "1-624-581-2345"
                        },
                        new
                        {
                            CustomerID = new Guid("06fce41f-e211-7f39-dae6-a85edd644d8c"),
                            BirthDate = new DateTime(2008, 11, 17, 8, 26, 14, 440, DateTimeKind.Local).AddTicks(8864),
                            EmailAddress = "Leticia99@yahoo.com",
                            FirstName = "Leticia",
                            LastName = "Roob",
                            Password = "59a96a32bc251374dc19163bd018c5a999a78b62",
                            PhoneNumber = "812-776-7367 x795"
                        },
                        new
                        {
                            CustomerID = new Guid("f660b7b7-1261-4395-05e8-c667c0dcb0e0"),
                            BirthDate = new DateTime(2015, 8, 31, 0, 38, 33, 293, DateTimeKind.Local).AddTicks(7372),
                            EmailAddress = "Grant.Murray85@gmail.com",
                            FirstName = "Grant",
                            LastName = "Murray",
                            Password = "863a9b36e82d44bcc42a67c85623660af7dee182",
                            PhoneNumber = "994-600-9838"
                        },
                        new
                        {
                            CustomerID = new Guid("f230b603-35fe-0d03-3ccc-c9cb9956aeaa"),
                            BirthDate = new DateTime(2007, 5, 16, 1, 40, 55, 636, DateTimeKind.Local).AddTicks(3012),
                            EmailAddress = "Molly.Rice26@gmail.com",
                            FirstName = "Molly",
                            LastName = "Rice",
                            Password = "85475c7011467ead61a278523c7ee23e23887119",
                            PhoneNumber = "476.747.0468"
                        },
                        new
                        {
                            CustomerID = new Guid("f5c512a0-02b7-5f57-fcbd-5ba893ac8846"),
                            BirthDate = new DateTime(2022, 8, 26, 10, 4, 16, 643, DateTimeKind.Local).AddTicks(9366),
                            EmailAddress = "Terrance_Wuckert@gmail.com",
                            FirstName = "Terrance",
                            LastName = "Wuckert",
                            Password = "4d9e755cdf3c31eb2795c84024c78cd0a2f12322",
                            PhoneNumber = "237.314.3880 x328"
                        },
                        new
                        {
                            CustomerID = new Guid("e8396ba4-038c-78b3-af6e-1aebe5b8b545"),
                            BirthDate = new DateTime(2010, 7, 8, 0, 27, 2, 192, DateTimeKind.Local).AddTicks(6465),
                            EmailAddress = "Brittany.Stroman@gmail.com",
                            FirstName = "Brittany",
                            LastName = "Stroman",
                            Password = "4de6f797ba3658bf1dde1f45bc3958958dfa9960",
                            PhoneNumber = "(220) 532-2971 x097"
                        },
                        new
                        {
                            CustomerID = new Guid("81e46d00-02f2-9bf3-1d64-34c8b0acd3f2"),
                            BirthDate = new DateTime(2008, 10, 6, 13, 38, 30, 331, DateTimeKind.Local).AddTicks(5434),
                            EmailAddress = "Roderick.OKon@yahoo.com",
                            FirstName = "Roderick",
                            LastName = "O'Kon",
                            Password = "e172ead6b13050f41dec6e537112eeab6379e513",
                            PhoneNumber = "(672) 952-7569"
                        },
                        new
                        {
                            CustomerID = new Guid("688f734c-e157-4fed-2679-1a5fe40fcbf0"),
                            BirthDate = new DateTime(2019, 7, 20, 0, 37, 46, 897, DateTimeKind.Local).AddTicks(1611),
                            EmailAddress = "Brent54@yahoo.com",
                            FirstName = "Brent",
                            LastName = "Bauch",
                            Password = "639a311882648c0d0c1980d7c31a94f85c644f65",
                            PhoneNumber = "501-941-2417 x4757"
                        },
                        new
                        {
                            CustomerID = new Guid("4a82c394-4d4f-be99-25dc-ddff23d837bb"),
                            BirthDate = new DateTime(2007, 10, 26, 11, 45, 34, 147, DateTimeKind.Local).AddTicks(6015),
                            EmailAddress = "Jennie_Renner@hotmail.com",
                            FirstName = "Jennie",
                            LastName = "Renner",
                            Password = "b7319de5b068b533be7e70a916ccb8bbc960054d",
                            PhoneNumber = "(864) 411-7717 x9370"
                        },
                        new
                        {
                            CustomerID = new Guid("f25bda5b-7435-2ca7-96d2-6fd66138ed95"),
                            BirthDate = new DateTime(2009, 7, 27, 13, 49, 53, 305, DateTimeKind.Local).AddTicks(4608),
                            EmailAddress = "Francisco95@yahoo.com",
                            FirstName = "Francisco",
                            LastName = "Boyer",
                            Password = "e794cfa40173cde865349b6fb6499c200514f6f6",
                            PhoneNumber = "1-777-387-2913"
                        },
                        new
                        {
                            CustomerID = new Guid("b893dfdf-9e7d-3f69-65b1-49b0c8db873d"),
                            BirthDate = new DateTime(2019, 3, 23, 18, 34, 14, 495, DateTimeKind.Local).AddTicks(1126),
                            EmailAddress = "Dominic_Witting@gmail.com",
                            FirstName = "Dominic",
                            LastName = "Witting",
                            Password = "ffbd00c1705f54965e603a6e9830530f1cb2c03d",
                            PhoneNumber = "856.831.1181 x496"
                        },
                        new
                        {
                            CustomerID = new Guid("754e551c-15c9-cc9e-9650-c2d39a59dc7f"),
                            BirthDate = new DateTime(2014, 2, 2, 0, 33, 26, 390, DateTimeKind.Local).AddTicks(170),
                            EmailAddress = "Marilyn40@yahoo.com",
                            FirstName = "Marilyn",
                            LastName = "Schmitt",
                            Password = "23a924ef0a616756fcc1145436b3a2d528183c6e",
                            PhoneNumber = "946-402-5786"
                        },
                        new
                        {
                            CustomerID = new Guid("bc845f40-9423-027c-a52a-b14ab961d03b"),
                            BirthDate = new DateTime(2022, 7, 11, 0, 49, 7, 1, DateTimeKind.Local).AddTicks(6734),
                            EmailAddress = "Warren93@hotmail.com",
                            FirstName = "Warren",
                            LastName = "Dach",
                            Password = "8d9a8794270f1464fc4e47a1e40e0ee4ae9db922",
                            PhoneNumber = "(348) 926-0215"
                        },
                        new
                        {
                            CustomerID = new Guid("7533aa4f-79c3-080e-0bac-be0428ab2aef"),
                            BirthDate = new DateTime(2007, 5, 22, 7, 35, 31, 523, DateTimeKind.Local).AddTicks(7745),
                            EmailAddress = "Ronnie_Wyman@gmail.com",
                            FirstName = "Ronnie",
                            LastName = "Wyman",
                            Password = "9f9d260c990cdb8e9ae662a88d40003aed75dc07",
                            PhoneNumber = "1-496-594-6226 x606"
                        },
                        new
                        {
                            CustomerID = new Guid("9a9b42a7-4ba4-b525-94c9-5b9a9b6369b3"),
                            BirthDate = new DateTime(2018, 12, 9, 12, 44, 58, 399, DateTimeKind.Local).AddTicks(3893),
                            EmailAddress = "Pat17@yahoo.com",
                            FirstName = "Pat",
                            LastName = "Greenfelder",
                            Password = "38a813a0511bbe75db6e5f9b9f935e09efb7214d",
                            PhoneNumber = "565.662.6862 x2202"
                        },
                        new
                        {
                            CustomerID = new Guid("75f7f787-b405-9689-9c36-cdcb1401eac5"),
                            BirthDate = new DateTime(2021, 12, 29, 7, 3, 42, 602, DateTimeKind.Local).AddTicks(3366),
                            EmailAddress = "Rickey_VonRueden@yahoo.com",
                            FirstName = "Rickey",
                            LastName = "VonRueden",
                            Password = "ccb476aac0ea148050b42c2877b1a038c28e5c0f",
                            PhoneNumber = "1-808-889-2331"
                        },
                        new
                        {
                            CustomerID = new Guid("2e345ac3-41be-81c2-3878-3544c9f48c19"),
                            BirthDate = new DateTime(2016, 7, 22, 1, 20, 51, 275, DateTimeKind.Local).AddTicks(8369),
                            EmailAddress = "Luke.Huels22@yahoo.com",
                            FirstName = "Luke",
                            LastName = "Huels",
                            Password = "15e51e4d3335884c3b6227a0cc72a638534c7fd1",
                            PhoneNumber = "(644) 391-0575"
                        },
                        new
                        {
                            CustomerID = new Guid("631e87eb-5da2-702e-60c1-17da93b98c32"),
                            BirthDate = new DateTime(2008, 12, 25, 3, 23, 14, 17, DateTimeKind.Local).AddTicks(4032),
                            EmailAddress = "Kelvin.Fahey@gmail.com",
                            FirstName = "Kelvin",
                            LastName = "Fahey",
                            Password = "b024e480737f94dd03013aa745cf98d7df4d54c4",
                            PhoneNumber = "866-896-8518 x9901"
                        },
                        new
                        {
                            CustomerID = new Guid("31971650-b99d-69e3-38c7-c99e03a8af46"),
                            BirthDate = new DateTime(2007, 9, 30, 17, 43, 51, 31, DateTimeKind.Local).AddTicks(114),
                            EmailAddress = "Blake53@gmail.com",
                            FirstName = "Blake",
                            LastName = "Johns",
                            Password = "bc07c285c7d69418cce0b98778628db1ce462643",
                            PhoneNumber = "983.543.9489"
                        },
                        new
                        {
                            CustomerID = new Guid("22772f46-c201-8a3b-02cc-b7f24d0bfa13"),
                            BirthDate = new DateTime(2006, 10, 30, 2, 29, 7, 370, DateTimeKind.Local).AddTicks(6218),
                            EmailAddress = "Felix_Ankunding87@hotmail.com",
                            FirstName = "Felix",
                            LastName = "Ankunding",
                            Password = "bfb9364fec046c65accd5da8e5fbf128c583f63c",
                            PhoneNumber = "501-645-3659 x0155"
                        },
                        new
                        {
                            CustomerID = new Guid("a15f21bc-4a12-d307-4f70-28fa46c9b08a"),
                            BirthDate = new DateTime(2016, 1, 18, 1, 38, 34, 902, DateTimeKind.Local).AddTicks(9116),
                            EmailAddress = "Celia_Lowe@yahoo.com",
                            FirstName = "Celia",
                            LastName = "Lowe",
                            Password = "c97416fdc34ec12e903b2e57b8bc6a60c157af00",
                            PhoneNumber = "392-463-7548 x0841"
                        },
                        new
                        {
                            CustomerID = new Guid("5609e9fe-c115-7d82-69f5-3e5570f10ab2"),
                            BirthDate = new DateTime(2017, 5, 9, 4, 12, 37, 28, DateTimeKind.Local).AddTicks(4765),
                            EmailAddress = "Alejandro_Johnson@hotmail.com",
                            FirstName = "Alejandro",
                            LastName = "Johnson",
                            Password = "7a9e05dab77d133af1ec90435df7b9b461898ccd",
                            PhoneNumber = "1-636-800-3880 x7955"
                        },
                        new
                        {
                            CustomerID = new Guid("3e8dd33e-1518-de51-7b10-19167b4659af"),
                            BirthDate = new DateTime(2017, 1, 26, 6, 23, 2, 8, DateTimeKind.Local).AddTicks(1867),
                            EmailAddress = "Percy_Haag@hotmail.com",
                            FirstName = "Percy",
                            LastName = "Haag",
                            Password = "4973de9386c244b1521045cddaf26bd93766f5dd",
                            PhoneNumber = "1-712-851-5804"
                        },
                        new
                        {
                            CustomerID = new Guid("fa9e7e15-74f3-b870-328b-5c3c51f5720c"),
                            BirthDate = new DateTime(2007, 3, 12, 10, 8, 10, 640, DateTimeKind.Local).AddTicks(5521),
                            EmailAddress = "Willie_McDermott16@yahoo.com",
                            FirstName = "Willie",
                            LastName = "McDermott",
                            Password = "375d307022037bbd48a2fdca0bb75ddd56da740e",
                            PhoneNumber = "1-321-998-9781"
                        },
                        new
                        {
                            CustomerID = new Guid("8770bd0c-97a4-973c-fc28-b7ca4085dcde"),
                            BirthDate = new DateTime(2016, 2, 25, 15, 0, 12, 815, DateTimeKind.Local).AddTicks(7272),
                            EmailAddress = "Meghan.Marvin44@gmail.com",
                            FirstName = "Meghan",
                            LastName = "Marvin",
                            Password = "10eb9093e308dfddb0c17d09aa4b687765cf4b77",
                            PhoneNumber = "(251) 426-5407"
                        },
                        new
                        {
                            CustomerID = new Guid("b8eff8bd-aadf-6c1f-a63a-93c8da63a6a1"),
                            BirthDate = new DateTime(2005, 6, 16, 1, 27, 36, 213, DateTimeKind.Local).AddTicks(5048),
                            EmailAddress = "Shelly_Wehner80@gmail.com",
                            FirstName = "Shelly",
                            LastName = "Wehner",
                            Password = "31299b245544b3b3705a9b18e801b9f717e5893f",
                            PhoneNumber = "(642) 949-1488 x036"
                        },
                        new
                        {
                            CustomerID = new Guid("dfd64567-9ec3-fd89-818f-b87ebb36fb67"),
                            BirthDate = new DateTime(2006, 11, 24, 12, 29, 37, 537, DateTimeKind.Local).AddTicks(9186),
                            EmailAddress = "Tyrone_Mertz43@gmail.com",
                            FirstName = "Tyrone",
                            LastName = "Mertz",
                            Password = "395c87b22cfc9e90bf004125adf0d286da3d4c56",
                            PhoneNumber = "1-514-814-8742"
                        },
                        new
                        {
                            CustomerID = new Guid("9ae34448-73d8-fc46-d5ce-e05850f2767d"),
                            BirthDate = new DateTime(2011, 1, 31, 0, 31, 38, 945, DateTimeKind.Local).AddTicks(1678),
                            EmailAddress = "Grady93@gmail.com",
                            FirstName = "Grady",
                            LastName = "Pouros",
                            Password = "3ac95e718d377da09f957f371a65c363ad88ebda",
                            PhoneNumber = "942.341.5558"
                        },
                        new
                        {
                            CustomerID = new Guid("f336e5c7-f171-d57a-57dc-4c80276401b0"),
                            BirthDate = new DateTime(2007, 6, 4, 5, 34, 50, 799, DateTimeKind.Local).AddTicks(8268),
                            EmailAddress = "Lydia.Bartoletti12@yahoo.com",
                            FirstName = "Lydia",
                            LastName = "Bartoletti",
                            Password = "8733470cbfb602e7f3f14a4c8df7f33d3289e39a",
                            PhoneNumber = "937.792.7942 x6992"
                        },
                        new
                        {
                            CustomerID = new Guid("48f8fa33-c460-0769-787f-ab41fd19024b"),
                            BirthDate = new DateTime(2020, 9, 30, 9, 27, 34, 258, DateTimeKind.Local).AddTicks(9088),
                            EmailAddress = "Regina.Tromp25@hotmail.com",
                            FirstName = "Regina",
                            LastName = "Tromp",
                            Password = "6312496fbab4543ba500ae03a2fe7d5ea4d01fa6",
                            PhoneNumber = "(718) 484-4344"
                        },
                        new
                        {
                            CustomerID = new Guid("8d4fb4fb-4e94-921f-2d4f-4bcb931ca066"),
                            BirthDate = new DateTime(2013, 11, 14, 9, 13, 7, 351, DateTimeKind.Local).AddTicks(6109),
                            EmailAddress = "Brent.Walker@gmail.com",
                            FirstName = "Brent",
                            LastName = "Walker",
                            Password = "3ae20ad3869be90020f99aeaf6db35101cd0a6e6",
                            PhoneNumber = "691-316-0592"
                        },
                        new
                        {
                            CustomerID = new Guid("f482dfd2-7dbc-861d-21c7-70d27bbe0116"),
                            BirthDate = new DateTime(2021, 2, 9, 23, 32, 29, 890, DateTimeKind.Local).AddTicks(7643),
                            EmailAddress = "Mercedes.Wunsch@hotmail.com",
                            FirstName = "Mercedes",
                            LastName = "Wunsch",
                            Password = "0808c811ba433b99fadbbd7ad5536be9197dbcbc",
                            PhoneNumber = "928-820-0322 x7822"
                        },
                        new
                        {
                            CustomerID = new Guid("8c593526-bcfa-08bf-2447-12a39d4eccf4"),
                            BirthDate = new DateTime(2012, 11, 7, 4, 59, 57, 90, DateTimeKind.Local).AddTicks(4865),
                            EmailAddress = "Eric_Hamill@gmail.com",
                            FirstName = "Eric",
                            LastName = "Hamill",
                            Password = "8e5a011121ce90938f2d55b92f24642d21d543c2",
                            PhoneNumber = "998-519-0752 x145"
                        },
                        new
                        {
                            CustomerID = new Guid("88816ec0-cb5f-e228-1154-607b26318e6f"),
                            BirthDate = new DateTime(2022, 2, 23, 2, 59, 48, 350, DateTimeKind.Local).AddTicks(94),
                            EmailAddress = "Dianne_Barton95@hotmail.com",
                            FirstName = "Dianne",
                            LastName = "Barton",
                            Password = "42f4c15100fe13775c6e7fe427b98b74c47b2536",
                            PhoneNumber = "1-399-611-2916 x7628"
                        },
                        new
                        {
                            CustomerID = new Guid("de28262a-5675-8830-6876-629c3019cd40"),
                            BirthDate = new DateTime(2016, 9, 11, 20, 24, 24, 453, DateTimeKind.Local).AddTicks(3912),
                            EmailAddress = "Jonathon47@gmail.com",
                            FirstName = "Jonathon",
                            LastName = "Mayer",
                            Password = "d7dc2676e45fb384e4c8b14249a0b9f2b5f50598",
                            PhoneNumber = "(464) 342-4780 x324"
                        },
                        new
                        {
                            CustomerID = new Guid("e6a72c6b-4fb0-5296-aaf7-dcf05c1e4e17"),
                            BirthDate = new DateTime(2013, 7, 17, 3, 20, 16, 553, DateTimeKind.Local).AddTicks(5570),
                            EmailAddress = "Candace60@gmail.com",
                            FirstName = "Candace",
                            LastName = "Kunze",
                            Password = "8c265f9f2d832691c5aa71124f515a442f35331c",
                            PhoneNumber = "1-333-669-0429"
                        },
                        new
                        {
                            CustomerID = new Guid("86cfb286-bdf6-2ed3-5e1b-5954890a56df"),
                            BirthDate = new DateTime(2016, 4, 11, 14, 59, 4, 268, DateTimeKind.Local).AddTicks(745),
                            EmailAddress = "Alonzo_Gleichner39@hotmail.com",
                            FirstName = "Alonzo",
                            LastName = "Gleichner",
                            Password = "9147031d2c913d25d8280473748dd2a5e58fab69",
                            PhoneNumber = "742-319-3749"
                        },
                        new
                        {
                            CustomerID = new Guid("9c47be26-995e-4348-ab4a-fe669f1713d7"),
                            BirthDate = new DateTime(2017, 11, 13, 18, 55, 37, 451, DateTimeKind.Local).AddTicks(5001),
                            EmailAddress = "Ira.Reinger@hotmail.com",
                            FirstName = "Ira",
                            LastName = "Reinger",
                            Password = "f571b78cd87b77737604075e220fb7c962246a54",
                            PhoneNumber = "1-666-856-9374 x45802"
                        },
                        new
                        {
                            CustomerID = new Guid("c5bb7180-9c3b-edf0-1866-85138bbab388"),
                            BirthDate = new DateTime(2006, 2, 27, 13, 14, 43, 635, DateTimeKind.Local).AddTicks(7359),
                            EmailAddress = "Sam_Kris@gmail.com",
                            FirstName = "Sam",
                            LastName = "Kris",
                            Password = "4e9e205b1d768dab1b06090bbcd0d1dc3a02c676",
                            PhoneNumber = "(554) 328-0954 x33387"
                        },
                        new
                        {
                            CustomerID = new Guid("86203469-a37f-7747-4d90-668c257eac37"),
                            BirthDate = new DateTime(2006, 9, 27, 7, 44, 33, 305, DateTimeKind.Local).AddTicks(8348),
                            EmailAddress = "Albert_Romaguera15@hotmail.com",
                            FirstName = "Albert",
                            LastName = "Romaguera",
                            Password = "cbc6390047a6a3f3c14d85c60396391e2e97b548",
                            PhoneNumber = "(571) 561-7709"
                        },
                        new
                        {
                            CustomerID = new Guid("8501a073-3b27-f999-c93f-7cb46f3af054"),
                            BirthDate = new DateTime(2005, 7, 10, 13, 53, 12, 39, DateTimeKind.Local).AddTicks(4950),
                            EmailAddress = "Isaac.Hammes@yahoo.com",
                            FirstName = "Isaac",
                            LastName = "Hammes",
                            Password = "dacaa5f2270709b69d4de6a09ddf0a9794596fae",
                            PhoneNumber = "(766) 614-1709"
                        },
                        new
                        {
                            CustomerID = new Guid("11d29de3-fa38-8668-8441-60d6e6ea087c"),
                            BirthDate = new DateTime(2017, 8, 13, 18, 10, 59, 30, DateTimeKind.Local).AddTicks(8194),
                            EmailAddress = "Gretchen.Goodwin@yahoo.com",
                            FirstName = "Gretchen",
                            LastName = "Goodwin",
                            Password = "c59c1e426192c211e1e04a122d4909a151253ced",
                            PhoneNumber = "(808) 891-7308 x34438"
                        },
                        new
                        {
                            CustomerID = new Guid("544c76db-88de-94ce-5d7a-bb8fa30c13bf"),
                            BirthDate = new DateTime(2017, 10, 27, 10, 47, 11, 305, DateTimeKind.Local).AddTicks(9017),
                            EmailAddress = "Faith.Hahn@gmail.com",
                            FirstName = "Faith",
                            LastName = "Hahn",
                            Password = "14704d53d9c817fbe9c812d68e3d85d46f30c103",
                            PhoneNumber = "235.600.6876 x18391"
                        },
                        new
                        {
                            CustomerID = new Guid("7a3175d3-3435-fc85-bd8f-b6266f574363"),
                            BirthDate = new DateTime(2007, 1, 13, 6, 18, 30, 614, DateTimeKind.Local).AddTicks(2043),
                            EmailAddress = "Ricardo_Hessel43@yahoo.com",
                            FirstName = "Ricardo",
                            LastName = "Hessel",
                            Password = "3a64c8331db08832f70cac407bb3725c6b338730",
                            PhoneNumber = "520-292-2752 x6133"
                        },
                        new
                        {
                            CustomerID = new Guid("a5a8e215-f788-ece7-a316-cd85e7167ba9"),
                            BirthDate = new DateTime(2019, 12, 20, 17, 9, 54, 500, DateTimeKind.Local).AddTicks(5487),
                            EmailAddress = "Margarita.Mosciski76@hotmail.com",
                            FirstName = "Margarita",
                            LastName = "Mosciski",
                            Password = "18d00e087f38ce1e24e8c14a4cb38d269ce837aa",
                            PhoneNumber = "(697) 950-5579"
                        },
                        new
                        {
                            CustomerID = new Guid("7b1a1654-2892-8ec2-8c3b-e35b78f2e405"),
                            BirthDate = new DateTime(2013, 6, 13, 15, 43, 12, 402, DateTimeKind.Local).AddTicks(1552),
                            EmailAddress = "Christie32@yahoo.com",
                            FirstName = "Christie",
                            LastName = "Homenick",
                            Password = "e654565f7bf4efa9c5a1f8f660d5030cb61ed9ce",
                            PhoneNumber = "554-238-8227"
                        },
                        new
                        {
                            CustomerID = new Guid("37209d80-f96c-1c43-f631-9a97293c4e9d"),
                            BirthDate = new DateTime(2010, 12, 20, 4, 13, 5, 630, DateTimeKind.Local).AddTicks(4686),
                            EmailAddress = "Erica.Hintz@hotmail.com",
                            FirstName = "Erica",
                            LastName = "Hintz",
                            Password = "692a9c05f11f8dbccd0f89646735823d45a7825f",
                            PhoneNumber = "1-573-999-4613"
                        },
                        new
                        {
                            CustomerID = new Guid("ec86c5cb-9bee-2b4b-2135-9295e1a914b0"),
                            BirthDate = new DateTime(2022, 7, 3, 8, 31, 34, 960, DateTimeKind.Local).AddTicks(2943),
                            EmailAddress = "Doyle_Lockman@gmail.com",
                            FirstName = "Doyle",
                            LastName = "Lockman",
                            Password = "d02cce6465ecef72cf90cb05b16bc2d1faa91ba8",
                            PhoneNumber = "249-754-0176"
                        },
                        new
                        {
                            CustomerID = new Guid("7db051ab-16a0-1c53-059b-8deeb6692244"),
                            BirthDate = new DateTime(2016, 12, 18, 2, 30, 40, 251, DateTimeKind.Local).AddTicks(5212),
                            EmailAddress = "Judith83@yahoo.com",
                            FirstName = "Judith",
                            LastName = "O'Hara",
                            Password = "9b71a29bb41d0e4118a11db9d72232c7aaecf6b3",
                            PhoneNumber = "1-235-656-9097"
                        },
                        new
                        {
                            CustomerID = new Guid("8afc72e0-3b97-2c79-59bc-2a19dd0e89ce"),
                            BirthDate = new DateTime(2007, 12, 8, 10, 43, 32, 777, DateTimeKind.Local).AddTicks(9413),
                            EmailAddress = "Kelley.Kirlin@gmail.com",
                            FirstName = "Kelley",
                            LastName = "Kirlin",
                            Password = "fe6add80a4bb8882b6cf66468ccfaba97e58c83f",
                            PhoneNumber = "(949) 731-4516 x663"
                        });
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Order", b =>
                {
                    b.Property<Guid>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BillingName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderID");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("BrandId");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.ProductCategory", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategory");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.ProductImage", b =>
                {
                    b.Property<Guid>("ProductImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductImageID");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImage", (string)null);
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Review", b =>
                {
                    b.Property<Guid>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReviewRating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReviewID");

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.ZipCode", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"), 1L, 1);

                    b.Property<string>("Commune")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ZipCodeID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Code");

                    b.ToTable("ZipCode", (string)null);
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Basket", b =>
                {
                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.BasketStatus", "BasketStatus")
                        .WithMany("Baskets")
                        .HasForeignKey("BasketStatusCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BasketStatus");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.BasketProduct", b =>
                {
                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.Basket", "Basket")
                        .WithMany("BasketProducts")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.Product", "Product")
                        .WithMany("BasketProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Basket");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Category", b =>
                {
                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.Category", null)
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryID1");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Product", b =>
                {
                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.ProductCategory", b =>
                {
                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.ProductImage", b =>
                {
                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Basket", b =>
                {
                    b.Navigation("BasketProducts");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.BasketStatus", b =>
                {
                    b.Navigation("Baskets");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Category", b =>
                {
                    b.Navigation("ProductCategories");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Product", b =>
                {
                    b.Navigation("BasketProducts");

                    b.Navigation("ProductCategories");

                    b.Navigation("ProductImages");
                });
#pragma warning restore 612, 618
        }
    }
}
