// <auto-generated />
using System;
using BodyRocky.Back.WebApi.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BodyRocky.Back.WebApi.Migrations
{
    [DbContext(typeof(BodyRockyDbContext))]
    [Migration("20221009200444_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Address", b =>
                {
                    b.Property<Guid>("AddressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddressFromDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AddressToDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<Guid>("ZipCodeID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AddressID");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ZipCodeID");

                    b.ToTable("Address", (string)null);
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Basket", b =>
                {
                    b.Property<Guid>("BasketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BasketDateAdded")
                        .HasColumnType("datetime2");

                    b.Property<int>("BasketStatusCode")
                        .HasColumnType("int");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BasketID");

                    b.HasIndex("BasketStatusCode");

                    b.HasIndex("CustomerId");

                    b.ToTable("Basket", (string)null);
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.BasketProduct", b =>
                {
                    b.Property<Guid>("BasketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("BasketId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("BasketProduct");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.BasketStatus", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("BasketStatus", (string)null);
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Brand", b =>
                {
                    b.Property<Guid>("BrandID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrandLogo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrandID");

                    b.ToTable("Brand", (string)null);
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Category", b =>
                {
                    b.Property<Guid>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.HasKey("CategoryID");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryID = new Guid("14e75b5e-ca71-f7ac-cd1d-fd123cb9c27e"),
                            CategoryName = "System.String[]",
                            IsFeatured = true
                        },
                        new
                        {
                            CategoryID = new Guid("c3557e91-f0f0-34a8-832a-6b6ab9d4516f"),
                            CategoryName = "System.String[]",
                            IsFeatured = false
                        },
                        new
                        {
                            CategoryID = new Guid("300ec048-a80d-9e7f-7d4f-6ee79e0446c0"),
                            CategoryName = "System.String[]",
                            IsFeatured = false
                        });
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Customer", b =>
                {
                    b.Property<Guid>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customer", (string)null);

                    b.HasData(
                        new
                        {
                            CustomerID = new Guid("5d35529f-88cd-71f0-a8c9-7c23594b42a6"),
                            BirthDate = new DateTime(2004, 11, 24, 18, 51, 51, 321, DateTimeKind.Local).AddTicks(2903),
                            EmailAddress = "Leonard.Kunze@yahoo.com",
                            FirstName = "Leonard",
                            LastName = "Kunze",
                            Password = "0045be1921a3fe7a7f38f54ea9457d0ae704d33a",
                            PhoneNumber = "318-363-4381"
                        },
                        new
                        {
                            CustomerID = new Guid("9b5834e3-a26c-1879-69b5-8e8334a65911"),
                            BirthDate = new DateTime(2017, 8, 7, 7, 13, 21, 261, DateTimeKind.Local).AddTicks(5166),
                            EmailAddress = "Doug54@yahoo.com",
                            FirstName = "Doug",
                            LastName = "Becker",
                            Password = "b80558efeca5b8f0d8c9259c7690f3e0e11905b7",
                            PhoneNumber = "842-993-4605"
                        },
                        new
                        {
                            CustomerID = new Guid("d6592505-0c71-0b6e-754f-2c537cff6332"),
                            BirthDate = new DateTime(2010, 5, 18, 14, 47, 48, 113, DateTimeKind.Local).AddTicks(1463),
                            EmailAddress = "Simon.Klocko36@hotmail.com",
                            FirstName = "Simon",
                            LastName = "Klocko",
                            Password = "db712c3592fb7f823d5a961779ce03e61e54cec6",
                            PhoneNumber = "1-608-813-4598"
                        },
                        new
                        {
                            CustomerID = new Guid("a522f1ad-d384-4b0c-68de-fa767f4858e8"),
                            BirthDate = new DateTime(2009, 7, 5, 19, 31, 39, 254, DateTimeKind.Local).AddTicks(5115),
                            EmailAddress = "Hilda_Larkin64@gmail.com",
                            FirstName = "Hilda",
                            LastName = "Larkin",
                            Password = "7881995e6ce7c1bc326b84e511425266dc42b87b",
                            PhoneNumber = "(800) 548-7854 x0775"
                        },
                        new
                        {
                            CustomerID = new Guid("fa748083-2efe-0c91-cead-91083d6bc187"),
                            BirthDate = new DateTime(2018, 2, 19, 2, 30, 46, 914, DateTimeKind.Local).AddTicks(6472),
                            EmailAddress = "Ann.Kunze68@yahoo.com",
                            FirstName = "Ann",
                            LastName = "Kunze",
                            Password = "4f5c9ffed9da0e7d6e3f223c50e63884f58191b6",
                            PhoneNumber = "275-658-0277"
                        },
                        new
                        {
                            CustomerID = new Guid("914cf295-3c6b-f005-9a4e-46704cd621bb"),
                            BirthDate = new DateTime(2019, 4, 20, 22, 13, 15, 837, DateTimeKind.Local).AddTicks(4607),
                            EmailAddress = "Neil15@yahoo.com",
                            FirstName = "Neil",
                            LastName = "Sauer",
                            Password = "7e21a47b7286a123ea9f332d81dd55c43db25d1b",
                            PhoneNumber = "(835) 351-4437 x3845"
                        },
                        new
                        {
                            CustomerID = new Guid("5e97d581-e859-e2f5-8644-b18013fefac5"),
                            BirthDate = new DateTime(2006, 1, 2, 2, 57, 37, 894, DateTimeKind.Local).AddTicks(6293),
                            EmailAddress = "Allen_Gaylord23@hotmail.com",
                            FirstName = "Allen",
                            LastName = "Gaylord",
                            Password = "340c21308c4d884f375338fcc1ae7d2b9fcac864",
                            PhoneNumber = "(312) 745-7263 x52653"
                        },
                        new
                        {
                            CustomerID = new Guid("1fd7a44c-7732-7509-dccc-682dc9114380"),
                            BirthDate = new DateTime(2018, 9, 6, 1, 13, 48, 75, DateTimeKind.Local).AddTicks(8051),
                            EmailAddress = "Alexander.Bailey@gmail.com",
                            FirstName = "Alexander",
                            LastName = "Bailey",
                            Password = "3409b392fe8d4feb1d3ab05643dc3b658a7e0e83",
                            PhoneNumber = "641-534-3591 x99585"
                        },
                        new
                        {
                            CustomerID = new Guid("1e288460-7bfd-6ff7-9a1c-454155552091"),
                            BirthDate = new DateTime(2016, 12, 24, 7, 2, 52, 135, DateTimeKind.Local).AddTicks(8362),
                            EmailAddress = "Eleanor35@hotmail.com",
                            FirstName = "Eleanor",
                            LastName = "Price",
                            Password = "607ad7d23a94e0f8413f896d1d088751da943396",
                            PhoneNumber = "1-308-226-0402 x9929"
                        },
                        new
                        {
                            CustomerID = new Guid("13de6330-6a43-1d18-9bc6-c99553f6c6ea"),
                            BirthDate = new DateTime(2020, 11, 28, 20, 33, 36, 325, DateTimeKind.Local).AddTicks(8089),
                            EmailAddress = "Glen_Hettinger@hotmail.com",
                            FirstName = "Glen",
                            LastName = "Hettinger",
                            Password = "6b6d9792d6a186e0e08677aa2b5401aaa8987ed8",
                            PhoneNumber = "(997) 629-5618"
                        },
                        new
                        {
                            CustomerID = new Guid("2c40526e-441b-c5fd-6d89-d6e6a286af8e"),
                            BirthDate = new DateTime(2015, 9, 13, 16, 22, 17, 639, DateTimeKind.Local).AddTicks(9433),
                            EmailAddress = "Marta90@yahoo.com",
                            FirstName = "Marta",
                            LastName = "McClure",
                            Password = "165c5d147a376117d7daaa04cf74ec42d1c21c1b",
                            PhoneNumber = "(285) 991-1620"
                        },
                        new
                        {
                            CustomerID = new Guid("6790061b-6bb5-a46f-d2bf-9ce6f7338fad"),
                            BirthDate = new DateTime(2015, 12, 27, 21, 45, 56, 707, DateTimeKind.Local).AddTicks(4534),
                            EmailAddress = "Jane.Jacobs82@hotmail.com",
                            FirstName = "Jane",
                            LastName = "Jacobs",
                            Password = "86573a2270c2903ee8378a2445fe0c62da8e627a",
                            PhoneNumber = "954-507-6496 x866"
                        },
                        new
                        {
                            CustomerID = new Guid("c8911711-a236-e640-2b65-f461be60af36"),
                            BirthDate = new DateTime(2011, 6, 14, 6, 31, 18, 471, DateTimeKind.Local).AddTicks(1661),
                            EmailAddress = "Calvin_Grady69@gmail.com",
                            FirstName = "Calvin",
                            LastName = "Grady",
                            Password = "ca83647df7ea57d9a28fb19ed9853d78ca5677de",
                            PhoneNumber = "1-333-749-7040"
                        },
                        new
                        {
                            CustomerID = new Guid("1b13bb98-5f3b-fffc-2491-2c8527402e36"),
                            BirthDate = new DateTime(2018, 4, 12, 6, 19, 49, 726, DateTimeKind.Local).AddTicks(4913),
                            EmailAddress = "Nellie_Marvin@yahoo.com",
                            FirstName = "Nellie",
                            LastName = "Marvin",
                            Password = "07a56367fbe23aab4a3b647fa2ff3a80a2695998",
                            PhoneNumber = "514-427-7064 x402"
                        },
                        new
                        {
                            CustomerID = new Guid("79e20778-3f38-dc35-01af-feee0ce344bb"),
                            BirthDate = new DateTime(2017, 1, 10, 6, 32, 56, 181, DateTimeKind.Local).AddTicks(6602),
                            EmailAddress = "Lola_Little@yahoo.com",
                            FirstName = "Lola",
                            LastName = "Little",
                            Password = "2670299ca4a9479951368b0b6e095a3807124f9f",
                            PhoneNumber = "1-730-832-3442 x747"
                        },
                        new
                        {
                            CustomerID = new Guid("4b59e25c-3b32-840c-9812-774484741577"),
                            BirthDate = new DateTime(2005, 5, 10, 1, 43, 35, 133, DateTimeKind.Local).AddTicks(6559),
                            EmailAddress = "Rudy77@hotmail.com",
                            FirstName = "Rudy",
                            LastName = "McCullough",
                            Password = "327f7baf9b7460b11a329aae2502508a3004d001",
                            PhoneNumber = "1-807-558-0527 x579"
                        },
                        new
                        {
                            CustomerID = new Guid("26790b56-e67f-a8a3-d082-101b31879cca"),
                            BirthDate = new DateTime(2017, 10, 13, 6, 14, 12, 160, DateTimeKind.Local).AddTicks(7611),
                            EmailAddress = "Charlotte_Durgan2@gmail.com",
                            FirstName = "Charlotte",
                            LastName = "Durgan",
                            Password = "eca6bbd2c785a550f0c0f7598be7b06cdd39d086",
                            PhoneNumber = "634-200-5716 x3043"
                        },
                        new
                        {
                            CustomerID = new Guid("b38d36e7-d41c-bf07-a5c2-428b367fb425"),
                            BirthDate = new DateTime(2007, 1, 11, 4, 23, 18, 184, DateTimeKind.Local).AddTicks(315),
                            EmailAddress = "Terence.Predovic10@yahoo.com",
                            FirstName = "Terence",
                            LastName = "Predovic",
                            Password = "263b633d52cbf183e142f2652e47d7a749335a8f",
                            PhoneNumber = "472.440.8875"
                        },
                        new
                        {
                            CustomerID = new Guid("318cd55c-1244-7af2-af67-3dbde16f1906"),
                            BirthDate = new DateTime(2009, 12, 6, 3, 7, 0, 411, DateTimeKind.Local).AddTicks(9551),
                            EmailAddress = "Clifford41@hotmail.com",
                            FirstName = "Clifford",
                            LastName = "Koch",
                            Password = "4ceae2842dea131ce684797fe49dc421fce519a3",
                            PhoneNumber = "468.203.1172 x9852"
                        },
                        new
                        {
                            CustomerID = new Guid("f105cf03-64d7-a7af-abc2-fc6510a0769e"),
                            BirthDate = new DateTime(2015, 5, 1, 15, 22, 45, 68, DateTimeKind.Local).AddTicks(8065),
                            EmailAddress = "David_Gaylord@gmail.com",
                            FirstName = "David",
                            LastName = "Gaylord",
                            Password = "b736578ace33b459230eba9d2dfec14257faf4eb",
                            PhoneNumber = "276.595.3664"
                        },
                        new
                        {
                            CustomerID = new Guid("edb0576d-d2c2-4d45-ffa4-4c1409c28be5"),
                            BirthDate = new DateTime(2006, 1, 26, 19, 9, 0, 500, DateTimeKind.Local).AddTicks(3170),
                            EmailAddress = "Timothy.Buckridge93@yahoo.com",
                            FirstName = "Timothy",
                            LastName = "Buckridge",
                            Password = "bc61ad75642f968231417231d7ca348e3aa19a15",
                            PhoneNumber = "1-431-403-9425"
                        },
                        new
                        {
                            CustomerID = new Guid("fe773a64-4c63-faf5-925f-7f12383b1a70"),
                            BirthDate = new DateTime(2012, 6, 9, 9, 28, 32, 345, DateTimeKind.Local).AddTicks(3397),
                            EmailAddress = "Lucas55@gmail.com",
                            FirstName = "Lucas",
                            LastName = "Towne",
                            Password = "4b400b889d8ced4d42f8becaafa41a947da4e25a",
                            PhoneNumber = "(280) 624-5600 x155"
                        },
                        new
                        {
                            CustomerID = new Guid("f91525ba-915d-f8e9-3215-5548c6734221"),
                            BirthDate = new DateTime(2017, 1, 21, 18, 49, 13, 661, DateTimeKind.Local).AddTicks(6273),
                            EmailAddress = "Estelle.Kemmer46@hotmail.com",
                            FirstName = "Estelle",
                            LastName = "Kemmer",
                            Password = "174b64975044ac784864a8917edd04b9dddee34b",
                            PhoneNumber = "1-560-649-4584 x69987"
                        },
                        new
                        {
                            CustomerID = new Guid("b44576d2-7324-ebb0-6683-5e48155940a4"),
                            BirthDate = new DateTime(2016, 3, 19, 7, 6, 17, 23, DateTimeKind.Local).AddTicks(5843),
                            EmailAddress = "Myrtle60@yahoo.com",
                            FirstName = "Myrtle",
                            LastName = "Stamm",
                            Password = "337762434e53f240219d14592629de3bbe367276",
                            PhoneNumber = "1-286-952-7726 x4118"
                        },
                        new
                        {
                            CustomerID = new Guid("cae30d77-523e-0e20-cb21-4b4963033269"),
                            BirthDate = new DateTime(2005, 4, 28, 1, 31, 29, 496, DateTimeKind.Local).AddTicks(9063),
                            EmailAddress = "Melody_Cormier@hotmail.com",
                            FirstName = "Melody",
                            LastName = "Cormier",
                            Password = "cba3d7f00e8abe2c1f61d26e42eacce4a3795bf0",
                            PhoneNumber = "(466) 573-6748"
                        },
                        new
                        {
                            CustomerID = new Guid("8367307b-6e92-29f0-7c4e-869d4a854be5"),
                            BirthDate = new DateTime(2007, 2, 1, 17, 41, 21, 827, DateTimeKind.Local).AddTicks(6145),
                            EmailAddress = "Carmen_Bartell74@yahoo.com",
                            FirstName = "Carmen",
                            LastName = "Bartell",
                            Password = "314eaf16119fb20f055afadc3927386efe7da948",
                            PhoneNumber = "(903) 220-9636"
                        },
                        new
                        {
                            CustomerID = new Guid("0f05a545-7e3c-110b-56a7-0ba775f6bfef"),
                            BirthDate = new DateTime(2006, 10, 24, 18, 5, 27, 479, DateTimeKind.Local).AddTicks(2605),
                            EmailAddress = "Tiffany_Rippin56@yahoo.com",
                            FirstName = "Tiffany",
                            LastName = "Rippin",
                            Password = "c23100418698c0c24995c8554f43525344b8f1d7",
                            PhoneNumber = "(919) 971-9792 x1466"
                        },
                        new
                        {
                            CustomerID = new Guid("f00709f3-8ecf-b810-2b1b-5e86fa2f79a9"),
                            BirthDate = new DateTime(2016, 7, 7, 9, 13, 18, 43, DateTimeKind.Local).AddTicks(6745),
                            EmailAddress = "Steve_Kuhn@gmail.com",
                            FirstName = "Steve",
                            LastName = "Kuhn",
                            Password = "03dc9a34023944bb0e36b9886345d22c9513e91e",
                            PhoneNumber = "1-574-679-2566 x244"
                        },
                        new
                        {
                            CustomerID = new Guid("3ad8e4c2-f62a-af55-0b18-6b817d9ecd32"),
                            BirthDate = new DateTime(2010, 11, 27, 13, 7, 54, 142, DateTimeKind.Local).AddTicks(2877),
                            EmailAddress = "Jermaine_Reilly55@hotmail.com",
                            FirstName = "Jermaine",
                            LastName = "Reilly",
                            Password = "bdaa518797bb0286d20f351e056039a60b140eaf",
                            PhoneNumber = "1-844-231-3091 x6379"
                        },
                        new
                        {
                            CustomerID = new Guid("e1226f27-c5bd-a3ec-61dc-16570a5931dc"),
                            BirthDate = new DateTime(2019, 8, 1, 10, 10, 25, 135, DateTimeKind.Local).AddTicks(6013),
                            EmailAddress = "Shannon.Cummings10@yahoo.com",
                            FirstName = "Shannon",
                            LastName = "Cummings",
                            Password = "6ad8d0ba80f1f2d9d59a174a5d8a13e627026ae8",
                            PhoneNumber = "822.686.4046"
                        },
                        new
                        {
                            CustomerID = new Guid("f034bb12-4909-c2f1-adc2-941ef392201e"),
                            BirthDate = new DateTime(2006, 4, 20, 17, 25, 24, 545, DateTimeKind.Local).AddTicks(4038),
                            EmailAddress = "Kristopher_Crooks@yahoo.com",
                            FirstName = "Kristopher",
                            LastName = "Crooks",
                            Password = "a78dc22921ac0ee5796e2efef9f700577ab91fd2",
                            PhoneNumber = "519-655-7666"
                        },
                        new
                        {
                            CustomerID = new Guid("17722116-7666-c310-6064-9033c277cab6"),
                            BirthDate = new DateTime(2006, 1, 31, 13, 26, 28, 798, DateTimeKind.Local).AddTicks(1688),
                            EmailAddress = "Florence.Rodriguez56@gmail.com",
                            FirstName = "Florence",
                            LastName = "Rodriguez",
                            Password = "0d2a5c5280df307f336888907d920b1963f13c3d",
                            PhoneNumber = "1-645-739-8811 x479"
                        },
                        new
                        {
                            CustomerID = new Guid("77b68bdb-d656-3ac3-6d09-52c4097837be"),
                            BirthDate = new DateTime(2015, 11, 6, 14, 0, 4, 496, DateTimeKind.Local).AddTicks(529),
                            EmailAddress = "Lora70@hotmail.com",
                            FirstName = "Lora",
                            LastName = "Fahey",
                            Password = "a78860048103de92bbc80343ee30cd4104246b5e",
                            PhoneNumber = "1-831-498-6465 x0154"
                        },
                        new
                        {
                            CustomerID = new Guid("674338f6-6508-5496-6dad-73ccdc3eb662"),
                            BirthDate = new DateTime(2005, 3, 19, 13, 4, 16, 462, DateTimeKind.Local).AddTicks(1405),
                            EmailAddress = "Shawn.Zieme43@hotmail.com",
                            FirstName = "Shawn",
                            LastName = "Zieme",
                            Password = "9277116941f77e140cd2733517a7e59d57548a57",
                            PhoneNumber = "752.806.4371"
                        },
                        new
                        {
                            CustomerID = new Guid("7fe6afbb-a564-0dd3-3645-3305d11ec7c5"),
                            BirthDate = new DateTime(2005, 7, 21, 18, 2, 34, 123, DateTimeKind.Local).AddTicks(329),
                            EmailAddress = "Blanca.Kozey@yahoo.com",
                            FirstName = "Blanca",
                            LastName = "Kozey",
                            Password = "e9e48d84cdb4215f70b94019712a3f244c126833",
                            PhoneNumber = "(380) 430-5156 x4121"
                        },
                        new
                        {
                            CustomerID = new Guid("72b14f87-b1b4-e850-9a25-4cdf7afd171c"),
                            BirthDate = new DateTime(2014, 11, 27, 6, 2, 49, 838, DateTimeKind.Local).AddTicks(969),
                            EmailAddress = "Kelvin3@gmail.com",
                            FirstName = "Kelvin",
                            LastName = "Bruen",
                            Password = "020a2a287abb1e06a1235bdc4bb91fd700e37bed",
                            PhoneNumber = "711.719.5093"
                        },
                        new
                        {
                            CustomerID = new Guid("2d6fa436-be81-f85b-8d9f-908ad558f401"),
                            BirthDate = new DateTime(2020, 10, 11, 4, 35, 15, 766, DateTimeKind.Local).AddTicks(533),
                            EmailAddress = "Jim_Schoen@gmail.com",
                            FirstName = "Jim",
                            LastName = "Schoen",
                            Password = "79c65d8671ce2ae3a096a16bab12d8a309c47092",
                            PhoneNumber = "(454) 429-9589 x383"
                        },
                        new
                        {
                            CustomerID = new Guid("923c700d-3098-e3d5-1caf-a2508bb09a91"),
                            BirthDate = new DateTime(2015, 6, 23, 8, 51, 22, 643, DateTimeKind.Local).AddTicks(1190),
                            EmailAddress = "Harvey_Mosciski92@yahoo.com",
                            FirstName = "Harvey",
                            LastName = "Mosciski",
                            Password = "bf28b652b6314f4c846a05f9c9028c8d99e9c81b",
                            PhoneNumber = "(262) 354-6155 x985"
                        },
                        new
                        {
                            CustomerID = new Guid("b48b6708-d6c4-d0e8-743a-1d9e15ebb3b8"),
                            BirthDate = new DateTime(2017, 10, 6, 6, 5, 49, 719, DateTimeKind.Local).AddTicks(8534),
                            EmailAddress = "Pablo63@gmail.com",
                            FirstName = "Pablo",
                            LastName = "Keebler",
                            Password = "2b183903d2d92a2650976fd79d475716efe8652e",
                            PhoneNumber = "(821) 966-8992"
                        },
                        new
                        {
                            CustomerID = new Guid("e806f965-9660-fb28-0646-f50ef243adbf"),
                            BirthDate = new DateTime(2020, 6, 15, 23, 28, 22, 83, DateTimeKind.Local).AddTicks(6522),
                            EmailAddress = "May.Baumbach59@hotmail.com",
                            FirstName = "May",
                            LastName = "Baumbach",
                            Password = "679c1718acb2b33217319f12541426ea769b6abc",
                            PhoneNumber = "316.612.7420 x46420"
                        },
                        new
                        {
                            CustomerID = new Guid("665236f5-5593-56fb-1fff-cbcbb8cf1676"),
                            BirthDate = new DateTime(2020, 6, 23, 20, 27, 1, 249, DateTimeKind.Local).AddTicks(3769),
                            EmailAddress = "Joel.Gerhold@hotmail.com",
                            FirstName = "Joel",
                            LastName = "Gerhold",
                            Password = "dda974875111902205cf590d708e26847f99c4fe",
                            PhoneNumber = "594-258-3866 x81410"
                        },
                        new
                        {
                            CustomerID = new Guid("7a7f3728-1d53-e7e3-86c6-78a4169e7677"),
                            BirthDate = new DateTime(2006, 1, 12, 1, 44, 19, 405, DateTimeKind.Local).AddTicks(8589),
                            EmailAddress = "Leona.Kuhn@yahoo.com",
                            FirstName = "Leona",
                            LastName = "Kuhn",
                            Password = "0190ad71046ff472d47f9cb222db718a24cdd2da",
                            PhoneNumber = "1-290-289-0323"
                        },
                        new
                        {
                            CustomerID = new Guid("83cc9d37-21ad-fff9-c5bf-a2ee22939a3d"),
                            BirthDate = new DateTime(2022, 8, 14, 20, 36, 10, 14, DateTimeKind.Local).AddTicks(4758),
                            EmailAddress = "Vicki12@hotmail.com",
                            FirstName = "Vicki",
                            LastName = "Kunze",
                            Password = "4704abc5e22d2323021769a034f0b25a00ba21a0",
                            PhoneNumber = "456.537.8613 x720"
                        },
                        new
                        {
                            CustomerID = new Guid("166c722e-215d-d794-0aee-4fb3de5f9a3c"),
                            BirthDate = new DateTime(2020, 10, 23, 6, 26, 44, 436, DateTimeKind.Local).AddTicks(3578),
                            EmailAddress = "Sandra.Jenkins65@gmail.com",
                            FirstName = "Sandra",
                            LastName = "Jenkins",
                            Password = "872328c3bb6ca412447d47b4c01d8b5f7b2ca00e",
                            PhoneNumber = "809.505.1203"
                        },
                        new
                        {
                            CustomerID = new Guid("f2a7bee5-0f00-1575-c0c5-333d77fa69ab"),
                            BirthDate = new DateTime(2010, 6, 13, 10, 11, 45, 236, DateTimeKind.Local).AddTicks(4256),
                            EmailAddress = "Joan29@hotmail.com",
                            FirstName = "Joan",
                            LastName = "Wisozk",
                            Password = "fe7fd4481b34d8a8920b91b3bd39489727d7c4e3",
                            PhoneNumber = "(328) 576-6124"
                        },
                        new
                        {
                            CustomerID = new Guid("1887f5f3-cc26-cfdd-7dd8-5b16058fab89"),
                            BirthDate = new DateTime(2016, 10, 22, 16, 26, 13, 538, DateTimeKind.Local).AddTicks(2263),
                            EmailAddress = "Estelle.Crona@gmail.com",
                            FirstName = "Estelle",
                            LastName = "Crona",
                            Password = "f69b6ae6d8379893c6950b787de4114c107d07df",
                            PhoneNumber = "1-942-599-1006"
                        },
                        new
                        {
                            CustomerID = new Guid("8fa5e7df-28ed-bc9a-964f-7144c47427c0"),
                            BirthDate = new DateTime(2013, 7, 20, 12, 47, 28, 82, DateTimeKind.Local).AddTicks(9737),
                            EmailAddress = "Krystal26@hotmail.com",
                            FirstName = "Krystal",
                            LastName = "Leffler",
                            Password = "e4794f55435df18240cc9b11c326372d27dd5611",
                            PhoneNumber = "(987) 597-0142"
                        },
                        new
                        {
                            CustomerID = new Guid("8c2b0ab7-554e-42e1-d70f-102cfd4994e4"),
                            BirthDate = new DateTime(2009, 5, 9, 10, 4, 38, 22, DateTimeKind.Local).AddTicks(2539),
                            EmailAddress = "Jan_Quitzon@gmail.com",
                            FirstName = "Jan",
                            LastName = "Quitzon",
                            Password = "982ba7fa63252fe2a68abdc716dda37a6c2f6c5e",
                            PhoneNumber = "658.940.2762"
                        },
                        new
                        {
                            CustomerID = new Guid("82ff0eb0-5cc8-22c3-a138-0a4c8f4eb707"),
                            BirthDate = new DateTime(2012, 10, 27, 17, 10, 17, 174, DateTimeKind.Local).AddTicks(7644),
                            EmailAddress = "Melba.Von@hotmail.com",
                            FirstName = "Melba",
                            LastName = "Von",
                            Password = "a35e7909a296becf77bbd9bfa1ac1dcfb9486775",
                            PhoneNumber = "209-843-5615 x4112"
                        },
                        new
                        {
                            CustomerID = new Guid("60e00bd2-5d3a-d8a1-18ac-ffae0d1997a7"),
                            BirthDate = new DateTime(2011, 1, 5, 7, 27, 49, 792, DateTimeKind.Local).AddTicks(2928),
                            EmailAddress = "Leland.Orn60@hotmail.com",
                            FirstName = "Leland",
                            LastName = "Orn",
                            Password = "e0d1c6a3adab7cfb65222a287c4a29297cc8867d",
                            PhoneNumber = "927.770.0531"
                        },
                        new
                        {
                            CustomerID = new Guid("dc6d3f5a-be01-1e67-2087-17f549c11633"),
                            BirthDate = new DateTime(2008, 3, 6, 1, 33, 4, 998, DateTimeKind.Local).AddTicks(8171),
                            EmailAddress = "Peggy.Sanford@hotmail.com",
                            FirstName = "Peggy",
                            LastName = "Sanford",
                            Password = "8a203f2255d620234eb51d9766e847dc3cf66d4c",
                            PhoneNumber = "244.456.1502"
                        },
                        new
                        {
                            CustomerID = new Guid("d269f076-1dd4-1891-f54b-6b892ecb3fce"),
                            BirthDate = new DateTime(2006, 8, 10, 18, 2, 7, 535, DateTimeKind.Local).AddTicks(6509),
                            EmailAddress = "Verna85@hotmail.com",
                            FirstName = "Verna",
                            LastName = "Cremin",
                            Password = "d130a534fc9798b7d2e72eef0eb94ad33205a023",
                            PhoneNumber = "334.472.5853"
                        },
                        new
                        {
                            CustomerID = new Guid("e10d43f7-6953-dad6-f02a-b9ad1bcbfc49"),
                            BirthDate = new DateTime(2020, 8, 9, 8, 39, 16, 483, DateTimeKind.Local).AddTicks(9082),
                            EmailAddress = "Rebecca.Abbott@gmail.com",
                            FirstName = "Rebecca",
                            LastName = "Abbott",
                            Password = "3746656bce5dde6cc9c34b05bdfa23e581f5bc4c",
                            PhoneNumber = "1-566-215-7373"
                        },
                        new
                        {
                            CustomerID = new Guid("9b736e17-2297-aef9-c10a-7681432a2e3c"),
                            BirthDate = new DateTime(2019, 2, 17, 3, 31, 39, 624, DateTimeKind.Local).AddTicks(5451),
                            EmailAddress = "Jeanette58@gmail.com",
                            FirstName = "Jeanette",
                            LastName = "Swaniawski",
                            Password = "5b1e78d6a9288701a59c46197ea60ef5ba2e724c",
                            PhoneNumber = "344.292.9046"
                        },
                        new
                        {
                            CustomerID = new Guid("b6881f12-1b7d-6c1c-21d0-f8cb221bb57f"),
                            BirthDate = new DateTime(2022, 6, 14, 3, 44, 23, 878, DateTimeKind.Local).AddTicks(7666),
                            EmailAddress = "Tyler.Windler28@hotmail.com",
                            FirstName = "Tyler",
                            LastName = "Windler",
                            Password = "707d90dbffad2ef3648c261a9c1a1d38b4e8e8d4",
                            PhoneNumber = "1-274-578-8682 x714"
                        },
                        new
                        {
                            CustomerID = new Guid("921b554a-e7e0-30c2-a4fc-7f65362b1239"),
                            BirthDate = new DateTime(2011, 12, 3, 10, 37, 26, 311, DateTimeKind.Local).AddTicks(1203),
                            EmailAddress = "Jordan_Macejkovic@gmail.com",
                            FirstName = "Jordan",
                            LastName = "Macejkovic",
                            Password = "e0193abf307d2dd01c424e8ed26f2566868e67bf",
                            PhoneNumber = "(825) 446-8998 x66145"
                        },
                        new
                        {
                            CustomerID = new Guid("358e5346-3c49-fda6-7d04-7315d16bc4b8"),
                            BirthDate = new DateTime(2015, 2, 5, 16, 2, 14, 835, DateTimeKind.Local).AddTicks(6363),
                            EmailAddress = "Israel_Beahan67@gmail.com",
                            FirstName = "Israel",
                            LastName = "Beahan",
                            Password = "3de81b796348eb339bc2392f72e14266033dfde8",
                            PhoneNumber = "408.608.6193"
                        },
                        new
                        {
                            CustomerID = new Guid("ec77729e-6676-3656-82d8-de42853fd33a"),
                            BirthDate = new DateTime(2020, 3, 18, 19, 30, 44, 502, DateTimeKind.Local).AddTicks(7010),
                            EmailAddress = "Marcia.Keeling24@gmail.com",
                            FirstName = "Marcia",
                            LastName = "Keeling",
                            Password = "04e4cbb2946085c2d6359a4a10f74420a0279be1",
                            PhoneNumber = "722.422.8499 x442"
                        },
                        new
                        {
                            CustomerID = new Guid("7f4392c4-f216-f9e6-cbc8-2a39d0dad87c"),
                            BirthDate = new DateTime(2005, 1, 22, 14, 20, 58, 789, DateTimeKind.Local).AddTicks(9315),
                            EmailAddress = "Lyle_Adams77@yahoo.com",
                            FirstName = "Lyle",
                            LastName = "Adams",
                            Password = "1e47a33cceb0075693a9e8b7fe867664b0b69ae0",
                            PhoneNumber = "(723) 210-3891"
                        },
                        new
                        {
                            CustomerID = new Guid("a35c6d9b-2dd7-f056-1390-a1b92bcbbe18"),
                            BirthDate = new DateTime(2011, 7, 13, 17, 18, 3, 49, DateTimeKind.Local).AddTicks(5839),
                            EmailAddress = "Kathryn_Schowalter@gmail.com",
                            FirstName = "Kathryn",
                            LastName = "Schowalter",
                            Password = "4ad1aa6cccc709cba8b7240da37ccff7b254d350",
                            PhoneNumber = "667-668-3088 x2864"
                        },
                        new
                        {
                            CustomerID = new Guid("6e79f291-87df-03ba-8471-e497f7c04f0c"),
                            BirthDate = new DateTime(2006, 6, 14, 0, 54, 58, 732, DateTimeKind.Local).AddTicks(9031),
                            EmailAddress = "Francis_Skiles78@yahoo.com",
                            FirstName = "Francis",
                            LastName = "Skiles",
                            Password = "5ff489e38f3999a2a0185bc5fcb30514a4f59af3",
                            PhoneNumber = "(923) 520-9976 x7661"
                        },
                        new
                        {
                            CustomerID = new Guid("139abff4-5859-02ca-ce02-8b8bf289569d"),
                            BirthDate = new DateTime(2020, 11, 26, 18, 3, 4, 59, DateTimeKind.Local).AddTicks(2547),
                            EmailAddress = "Hugo19@hotmail.com",
                            FirstName = "Hugo",
                            LastName = "Dare",
                            Password = "be248cc0474c0245c233629c7336789e86a7975f",
                            PhoneNumber = "296-382-0636"
                        },
                        new
                        {
                            CustomerID = new Guid("f7163aa1-4ebe-9191-1bd5-e8dd8263ef60"),
                            BirthDate = new DateTime(2020, 10, 19, 4, 26, 33, 720, DateTimeKind.Local).AddTicks(6996),
                            EmailAddress = "Tabitha_Stark@yahoo.com",
                            FirstName = "Tabitha",
                            LastName = "Stark",
                            Password = "93f10c182fa04ed21c5f71d08190dca286b20ed4",
                            PhoneNumber = "605.453.2490"
                        },
                        new
                        {
                            CustomerID = new Guid("4bfa3efb-aa1b-5616-d1ef-e72799aaf0a0"),
                            BirthDate = new DateTime(2005, 6, 15, 18, 13, 43, 558, DateTimeKind.Local).AddTicks(4239),
                            EmailAddress = "Leona_Lowe94@gmail.com",
                            FirstName = "Leona",
                            LastName = "Lowe",
                            Password = "abec71d56a10f3a24e4f2ac0b7f6f6a1f2490987",
                            PhoneNumber = "325-484-5321"
                        },
                        new
                        {
                            CustomerID = new Guid("a183b39c-9a2f-a4b2-34cc-a02d3c7b3251"),
                            BirthDate = new DateTime(2020, 11, 15, 11, 13, 0, 228, DateTimeKind.Local).AddTicks(3502),
                            EmailAddress = "Linda_Schumm@yahoo.com",
                            FirstName = "Linda",
                            LastName = "Schumm",
                            Password = "878b1b3174f715b21fc5786778a14bd1b94aa01c",
                            PhoneNumber = "703.475.3885"
                        },
                        new
                        {
                            CustomerID = new Guid("f2ef8ca1-7906-a130-4a70-966bf14347f5"),
                            BirthDate = new DateTime(2018, 9, 19, 17, 48, 23, 688, DateTimeKind.Local).AddTicks(8670),
                            EmailAddress = "Fredrick0@gmail.com",
                            FirstName = "Fredrick",
                            LastName = "Ondricka",
                            Password = "75658f844f9f7d90ef0a3d79f5143bad5265d2b8",
                            PhoneNumber = "(583) 764-7407 x002"
                        },
                        new
                        {
                            CustomerID = new Guid("fc0c298c-fe98-d672-b7e8-baf6c510d0cc"),
                            BirthDate = new DateTime(2013, 1, 20, 22, 42, 37, 212, DateTimeKind.Local).AddTicks(1526),
                            EmailAddress = "Jessica.Heller@gmail.com",
                            FirstName = "Jessica",
                            LastName = "Heller",
                            Password = "0f2662d2fdc4d97af50108ef48516183d828f053",
                            PhoneNumber = "1-898-921-6036 x50220"
                        },
                        new
                        {
                            CustomerID = new Guid("7349a633-7f05-836c-94f3-fea3b4855ded"),
                            BirthDate = new DateTime(2011, 7, 8, 3, 41, 59, 206, DateTimeKind.Local).AddTicks(2550),
                            EmailAddress = "Josh.Abshire43@hotmail.com",
                            FirstName = "Josh",
                            LastName = "Abshire",
                            Password = "8fa931853d5940c979a61da0882b062544143f6f",
                            PhoneNumber = "440.989.1858 x03511"
                        },
                        new
                        {
                            CustomerID = new Guid("93cec1ad-8cde-c1b2-530c-f5c72fe02d38"),
                            BirthDate = new DateTime(2013, 11, 2, 13, 2, 27, 204, DateTimeKind.Local).AddTicks(742),
                            EmailAddress = "Cody87@hotmail.com",
                            FirstName = "Cody",
                            LastName = "Wiegand",
                            Password = "ca60d2b2287a08f8c3f29957c0dc05b141cd69b1",
                            PhoneNumber = "702.572.1582"
                        },
                        new
                        {
                            CustomerID = new Guid("8642178f-49f0-920c-b7a4-7e13b4aa8521"),
                            BirthDate = new DateTime(2007, 4, 7, 8, 4, 2, 826, DateTimeKind.Local).AddTicks(4116),
                            EmailAddress = "Clay_Lang@hotmail.com",
                            FirstName = "Clay",
                            LastName = "Lang",
                            Password = "b754bef0d426358523d0bf5603376c6e99264681",
                            PhoneNumber = "847.459.1965 x94106"
                        },
                        new
                        {
                            CustomerID = new Guid("c5c022f1-cee8-ba08-d3f0-826e3c2ee9ae"),
                            BirthDate = new DateTime(2006, 1, 28, 7, 38, 49, 642, DateTimeKind.Local).AddTicks(7282),
                            EmailAddress = "Christina_Pfannerstill@yahoo.com",
                            FirstName = "Christina",
                            LastName = "Pfannerstill",
                            Password = "949865c911ba1467fdabcc294cf719be0f998c61",
                            PhoneNumber = "822.307.6869 x4635"
                        },
                        new
                        {
                            CustomerID = new Guid("0eaa4c37-888a-1c2e-b2b8-50574e0f4378"),
                            BirthDate = new DateTime(2007, 8, 11, 18, 12, 3, 823, DateTimeKind.Local).AddTicks(58),
                            EmailAddress = "Iris.Doyle16@yahoo.com",
                            FirstName = "Iris",
                            LastName = "Doyle",
                            Password = "2283fb5477c8e2e3c77666e933b51c83dfac5591",
                            PhoneNumber = "(408) 791-4137 x717"
                        },
                        new
                        {
                            CustomerID = new Guid("c4f5569e-8e92-b165-bd2f-9b235adf5988"),
                            BirthDate = new DateTime(2006, 8, 25, 15, 27, 58, 195, DateTimeKind.Local).AddTicks(511),
                            EmailAddress = "Mario_Gleichner@gmail.com",
                            FirstName = "Mario",
                            LastName = "Gleichner",
                            Password = "3206a82a0b1e277092a05b96843b2059774643b1",
                            PhoneNumber = "(767) 601-8809 x30964"
                        },
                        new
                        {
                            CustomerID = new Guid("add1aa11-3482-1e0b-0de5-d10240bd9b5b"),
                            BirthDate = new DateTime(2011, 12, 30, 5, 42, 43, 326, DateTimeKind.Local).AddTicks(7013),
                            EmailAddress = "Emanuel_Beatty@hotmail.com",
                            FirstName = "Emanuel",
                            LastName = "Beatty",
                            Password = "cd17bb09049959c224ebddbc49d3b1ea39572afd",
                            PhoneNumber = "(528) 848-8732"
                        },
                        new
                        {
                            CustomerID = new Guid("130cfdc4-27d3-11c1-cb5e-0737ad9e4e7b"),
                            BirthDate = new DateTime(2009, 8, 19, 13, 11, 15, 966, DateTimeKind.Local).AddTicks(3527),
                            EmailAddress = "Ginger_Hyatt60@yahoo.com",
                            FirstName = "Ginger",
                            LastName = "Hyatt",
                            Password = "fb3b9c1baa029a637f6f11c667c95f88ae90c0bd",
                            PhoneNumber = "1-274-838-1174 x55109"
                        },
                        new
                        {
                            CustomerID = new Guid("2bd9c2e4-985e-592d-1fa4-bab3891fd488"),
                            BirthDate = new DateTime(2020, 7, 12, 23, 13, 31, 489, DateTimeKind.Local).AddTicks(9607),
                            EmailAddress = "Cheryl_Witting44@yahoo.com",
                            FirstName = "Cheryl",
                            LastName = "Witting",
                            Password = "439a88eebff03f72125c27f49cbdc48056a5a369",
                            PhoneNumber = "(829) 928-0658 x95195"
                        },
                        new
                        {
                            CustomerID = new Guid("425edfe9-e507-5774-1f88-556c0879e46c"),
                            BirthDate = new DateTime(2011, 11, 19, 22, 37, 32, 338, DateTimeKind.Local).AddTicks(1312),
                            EmailAddress = "Hope.Beier@hotmail.com",
                            FirstName = "Hope",
                            LastName = "Beier",
                            Password = "8126e1baa34601145f5b128498fd20297cf9ea92",
                            PhoneNumber = "811-341-7564 x65437"
                        },
                        new
                        {
                            CustomerID = new Guid("3122cc02-9ddc-1296-6e41-e12608972daa"),
                            BirthDate = new DateTime(2010, 10, 3, 8, 28, 51, 995, DateTimeKind.Local).AddTicks(5173),
                            EmailAddress = "Tim.Sanford82@yahoo.com",
                            FirstName = "Tim",
                            LastName = "Sanford",
                            Password = "a3fe5f9e05b8bcac690584043b4c800bb93020dd",
                            PhoneNumber = "920.902.6132 x00816"
                        },
                        new
                        {
                            CustomerID = new Guid("fba260f4-1221-1adc-3f0c-59fbfd516aad"),
                            BirthDate = new DateTime(2020, 2, 25, 15, 17, 2, 220, DateTimeKind.Local).AddTicks(5442),
                            EmailAddress = "Alejandro74@gmail.com",
                            FirstName = "Alejandro",
                            LastName = "Price",
                            Password = "604f258a45dacb1a276ff675dcec01b63c26d8b2",
                            PhoneNumber = "1-356-249-7643"
                        },
                        new
                        {
                            CustomerID = new Guid("61dc6d3e-9309-313b-3aaa-07d534f58418"),
                            BirthDate = new DateTime(2015, 3, 10, 11, 23, 39, 722, DateTimeKind.Local).AddTicks(6779),
                            EmailAddress = "Clint84@yahoo.com",
                            FirstName = "Clint",
                            LastName = "Kertzmann",
                            Password = "2616e6e2949503c09c98239ebd2c569d98d26948",
                            PhoneNumber = "807-466-3298 x4481"
                        },
                        new
                        {
                            CustomerID = new Guid("8c560cbf-eaac-4207-d64b-123ed6b4f014"),
                            BirthDate = new DateTime(2022, 2, 2, 14, 52, 30, 429, DateTimeKind.Local).AddTicks(6510),
                            EmailAddress = "Amelia_Hammes@gmail.com",
                            FirstName = "Amelia",
                            LastName = "Hammes",
                            Password = "42a0263fce2c12202359899303908b3d1c5b4a94",
                            PhoneNumber = "(273) 360-4099"
                        },
                        new
                        {
                            CustomerID = new Guid("4f98aa83-2133-f94f-4e6e-c3b4a51120b4"),
                            BirthDate = new DateTime(2008, 2, 10, 21, 26, 30, 87, DateTimeKind.Local).AddTicks(4803),
                            EmailAddress = "Derrick_Abbott@gmail.com",
                            FirstName = "Derrick",
                            LastName = "Abbott",
                            Password = "9fa18e0a8457c5dc8ad74ef7760565f638bb8ede",
                            PhoneNumber = "(619) 443-4275 x115"
                        },
                        new
                        {
                            CustomerID = new Guid("17bee96f-56e3-b67f-7690-ed787f187a4b"),
                            BirthDate = new DateTime(2012, 3, 6, 17, 16, 8, 30, DateTimeKind.Local).AddTicks(9037),
                            EmailAddress = "Mark.Collier16@yahoo.com",
                            FirstName = "Mark",
                            LastName = "Collier",
                            Password = "08896a844501c2efabb1134cac8e183bb2b8e76b",
                            PhoneNumber = "305-846-6384"
                        },
                        new
                        {
                            CustomerID = new Guid("e4e56dbe-26d1-aa52-7d3c-fc9bb76890d9"),
                            BirthDate = new DateTime(2007, 11, 1, 9, 19, 54, 759, DateTimeKind.Local).AddTicks(5510),
                            EmailAddress = "Preston75@yahoo.com",
                            FirstName = "Preston",
                            LastName = "King",
                            Password = "19cae0a6ea3c4fe799756c562d9f36614dfbdbfb",
                            PhoneNumber = "(765) 922-4641 x8681"
                        },
                        new
                        {
                            CustomerID = new Guid("cd984c84-5092-2d6a-647e-4f89a3342dec"),
                            BirthDate = new DateTime(2007, 11, 30, 15, 24, 27, 697, DateTimeKind.Local).AddTicks(3245),
                            EmailAddress = "Jared_Langworth@yahoo.com",
                            FirstName = "Jared",
                            LastName = "Langworth",
                            Password = "fc2a065a676cc655ad48abe9987c99f87436ed8e",
                            PhoneNumber = "1-333-478-1484"
                        },
                        new
                        {
                            CustomerID = new Guid("0befa4e5-518e-64e5-13a2-852413c3fc79"),
                            BirthDate = new DateTime(2006, 6, 3, 0, 51, 13, 701, DateTimeKind.Local).AddTicks(2195),
                            EmailAddress = "Clifton37@hotmail.com",
                            FirstName = "Clifton",
                            LastName = "Wisozk",
                            Password = "cf21b0d735c47fb5f92defc66b7e20db1f84728a",
                            PhoneNumber = "(722) 554-2550"
                        },
                        new
                        {
                            CustomerID = new Guid("16212585-a5aa-cf80-69a3-599ad5bb32d6"),
                            BirthDate = new DateTime(2014, 10, 29, 12, 4, 15, 423, DateTimeKind.Local).AddTicks(8977),
                            EmailAddress = "Virginia_Kessler13@gmail.com",
                            FirstName = "Virginia",
                            LastName = "Kessler",
                            Password = "00f2822485739c9b0fad922761c799904684003c",
                            PhoneNumber = "895.616.1373 x36767"
                        },
                        new
                        {
                            CustomerID = new Guid("f57d7f01-282c-7433-3820-021d9e1c578c"),
                            BirthDate = new DateTime(2016, 11, 6, 17, 28, 40, 95, DateTimeKind.Local).AddTicks(2970),
                            EmailAddress = "Ruben19@gmail.com",
                            FirstName = "Ruben",
                            LastName = "Hayes",
                            Password = "6039df4e64fcf19fe21d36d3c6707a0c225f73ad",
                            PhoneNumber = "548-482-3914 x968"
                        },
                        new
                        {
                            CustomerID = new Guid("8e327c2d-9f60-2696-89b8-93e7c092b065"),
                            BirthDate = new DateTime(2020, 11, 15, 3, 0, 28, 827, DateTimeKind.Local).AddTicks(7057),
                            EmailAddress = "Eleanor89@yahoo.com",
                            FirstName = "Eleanor",
                            LastName = "Thompson",
                            Password = "e0e6d043e7423c531d34a1165e0911cae67c956e",
                            PhoneNumber = "(537) 201-8655"
                        },
                        new
                        {
                            CustomerID = new Guid("ffa97ff7-14e6-9009-05b1-432517ef0dac"),
                            BirthDate = new DateTime(2017, 12, 2, 2, 52, 0, 792, DateTimeKind.Local).AddTicks(8626),
                            EmailAddress = "Simon60@yahoo.com",
                            FirstName = "Simon",
                            LastName = "Boyer",
                            Password = "4bcb24df762e443ba259ddfe67aa3206e75d4005",
                            PhoneNumber = "697-313-2959 x176"
                        },
                        new
                        {
                            CustomerID = new Guid("4da5bdaf-d232-b944-aa4a-dfd426ff3aa3"),
                            BirthDate = new DateTime(2007, 2, 23, 16, 13, 44, 243, DateTimeKind.Local).AddTicks(6330),
                            EmailAddress = "Flora_Morar77@hotmail.com",
                            FirstName = "Flora",
                            LastName = "Morar",
                            Password = "902eab78a756c83dc05ee4f0a15343d29245d372",
                            PhoneNumber = "263-319-2438"
                        },
                        new
                        {
                            CustomerID = new Guid("a8fb8823-658c-fe5c-3bdc-93feaea53cd8"),
                            BirthDate = new DateTime(2021, 12, 13, 10, 25, 14, 234, DateTimeKind.Local).AddTicks(9538),
                            EmailAddress = "Desiree78@yahoo.com",
                            FirstName = "Desiree",
                            LastName = "Treutel",
                            Password = "320486a24116786f759f1871811b72e2c0c99e14",
                            PhoneNumber = "1-704-958-8618"
                        },
                        new
                        {
                            CustomerID = new Guid("d3d81b43-68d5-aaae-3d07-98bac322e53b"),
                            BirthDate = new DateTime(2017, 11, 29, 21, 58, 3, 889, DateTimeKind.Local).AddTicks(6567),
                            EmailAddress = "Michael_Morissette@yahoo.com",
                            FirstName = "Michael",
                            LastName = "Morissette",
                            Password = "0ceb54499b2d68027a7ad5620296f0f700b06bce",
                            PhoneNumber = "(347) 543-4317 x990"
                        },
                        new
                        {
                            CustomerID = new Guid("6998dc98-02b8-4b9a-4e45-9d60700ca66e"),
                            BirthDate = new DateTime(2007, 2, 24, 4, 29, 44, 144, DateTimeKind.Local).AddTicks(3464),
                            EmailAddress = "Everett91@hotmail.com",
                            FirstName = "Everett",
                            LastName = "Crona",
                            Password = "2237d32ec005f1685efd7e460bbc6ab4a3e9e9ff",
                            PhoneNumber = "1-834-267-0772 x1485"
                        },
                        new
                        {
                            CustomerID = new Guid("f3d5b49c-62e0-db74-c54a-7b17c09d5a47"),
                            BirthDate = new DateTime(2005, 4, 7, 8, 31, 44, 229, DateTimeKind.Local).AddTicks(5834),
                            EmailAddress = "Darrel.DAmore97@yahoo.com",
                            FirstName = "Darrel",
                            LastName = "D'Amore",
                            Password = "34983a885aa966e7a3a4d4a53b78cc153da3affe",
                            PhoneNumber = "269.677.3432"
                        },
                        new
                        {
                            CustomerID = new Guid("cd282a1e-18ce-f105-c102-449ffada84d2"),
                            BirthDate = new DateTime(2010, 8, 19, 7, 9, 33, 264, DateTimeKind.Local).AddTicks(9592),
                            EmailAddress = "Angel64@gmail.com",
                            FirstName = "Angel",
                            LastName = "Schmitt",
                            Password = "9138d5e81a684f2ffe356568e269b6e4834af4ad",
                            PhoneNumber = "1-276-476-9385 x03192"
                        },
                        new
                        {
                            CustomerID = new Guid("89c2d2dd-b15e-adcf-3b17-0944672ae76c"),
                            BirthDate = new DateTime(2018, 4, 20, 7, 20, 41, 57, DateTimeKind.Local).AddTicks(2484),
                            EmailAddress = "Darin_Hoppe@hotmail.com",
                            FirstName = "Darin",
                            LastName = "Hoppe",
                            Password = "bea16bff5c70b5e771d7d15dbc82be166cede0f6",
                            PhoneNumber = "(371) 901-8737"
                        },
                        new
                        {
                            CustomerID = new Guid("1ec6f25f-da03-aa9c-ede1-aae5b188aca0"),
                            BirthDate = new DateTime(2018, 12, 30, 0, 20, 47, 420, DateTimeKind.Local).AddTicks(7717),
                            EmailAddress = "Christina.Quitzon40@yahoo.com",
                            FirstName = "Christina",
                            LastName = "Quitzon",
                            Password = "77a7ab35c2d2dbbfca9555b8e71b1bde3e677f91",
                            PhoneNumber = "232-679-8272"
                        },
                        new
                        {
                            CustomerID = new Guid("d19eb9df-2bc0-a38b-e4b1-ff657b3fcea3"),
                            BirthDate = new DateTime(2015, 3, 27, 16, 15, 13, 363, DateTimeKind.Local).AddTicks(7568),
                            EmailAddress = "Inez_King@hotmail.com",
                            FirstName = "Inez",
                            LastName = "King",
                            Password = "0cf2a69c068512ad5bb56306cba09909104e94b3",
                            PhoneNumber = "(569) 690-5541 x9563"
                        },
                        new
                        {
                            CustomerID = new Guid("31397f73-5f10-7346-f079-fcf82bbe6e4c"),
                            BirthDate = new DateTime(2008, 5, 12, 2, 23, 49, 122, DateTimeKind.Local).AddTicks(9542),
                            EmailAddress = "Daryl.Nolan@gmail.com",
                            FirstName = "Daryl",
                            LastName = "Nolan",
                            Password = "f3ebe446ddf95ba5a5c9b3e9b73861b958a8cddc",
                            PhoneNumber = "(249) 512-7055"
                        });
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Order", b =>
                {
                    b.Property<Guid>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BillingAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BillingName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeliveryAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeliveryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderStatusCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderID");

                    b.HasIndex("BillingAddressId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DeliveryAddressId");

                    b.HasIndex("OrderStatusCode");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.OrderedProduct", b =>
                {
                    b.Property<Guid>("OrderedProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OrderedProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderedProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OrderedProductPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderedProductId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderedProduct", (string)null);
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.OrderStatus", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("OrderStatus", (string)null);
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ProductURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("BrandId");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.ProductCategory", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategory");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.ProductImage", b =>
                {
                    b.Property<Guid>("ProductImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductImageID");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImage", (string)null);
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Review", b =>
                {
                    b.Property<Guid>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReviewRating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReviewID");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.ZipCode", b =>
                {
                    b.Property<Guid>("ZipCodeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Commune")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ZipCodeID");

                    b.HasIndex("Code", "Commune")
                        .IsUnique();

                    b.ToTable("ZipCode", (string)null);
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Address", b =>
                {
                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.ZipCode", "ZipCode")
                        .WithMany("Addresses")
                        .HasForeignKey("ZipCodeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("ZipCode");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Basket", b =>
                {
                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.BasketStatus", "BasketStatus")
                        .WithMany("Baskets")
                        .HasForeignKey("BasketStatusCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.Customer", "Customer")
                        .WithMany("Baskets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BasketStatus");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.BasketProduct", b =>
                {
                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.Basket", "Basket")
                        .WithMany("BasketProducts")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.Product", "Product")
                        .WithMany("BasketProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Basket");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Order", b =>
                {
                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.Address", "BillingAddress")
                        .WithMany("BilledOrders")
                        .HasForeignKey("BillingAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.Address", "DeliveryAddress")
                        .WithMany("DeliveredOrders")
                        .HasForeignKey("DeliveryAddressId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.OrderStatus", "OrderStatus")
                        .WithMany("Orders")
                        .HasForeignKey("OrderStatusCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillingAddress");

                    b.Navigation("Customer");

                    b.Navigation("DeliveryAddress");

                    b.Navigation("OrderStatus");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.OrderedProduct", b =>
                {
                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.Order", "Order")
                        .WithMany("OrderedProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.Product", "Product")
                        .WithMany("OrderedProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Product", b =>
                {
                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.ProductCategory", b =>
                {
                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.ProductImage", b =>
                {
                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Review", b =>
                {
                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.Customer", "Customer")
                        .WithMany("Reviews")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Address", b =>
                {
                    b.Navigation("BilledOrders");

                    b.Navigation("DeliveredOrders");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Basket", b =>
                {
                    b.Navigation("BasketProducts");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.BasketStatus", b =>
                {
                    b.Navigation("Baskets");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Category", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Baskets");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Order", b =>
                {
                    b.Navigation("OrderedProducts");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.OrderStatus", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Product", b =>
                {
                    b.Navigation("BasketProducts");

                    b.Navigation("OrderedProducts");

                    b.Navigation("ProductCategories");

                    b.Navigation("ProductImages");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.ZipCode", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
