// <auto-generated />
using System;
using BodyRocky.Back.WebApi.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BodyRocky.Back.WebApi.Migrations
{
    [DbContext(typeof(BodyRockyDbContext))]
    [Migration("20221009153905_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Address", b =>
                {
                    b.Property<Guid>("AddressID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddressFromDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AddressToDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("ZipCodeID")
                        .HasColumnType("int");

                    b.HasKey("AddressID");

                    b.HasIndex("ZipCodeID");

                    b.ToTable("Address", (string)null);
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Basket", b =>
                {
                    b.Property<Guid>("BasketID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BasketDateAdded")
                        .HasColumnType("datetime2");

                    b.Property<int>("BasketStatusCode")
                        .HasColumnType("int");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BasketID");

                    b.HasIndex("BasketStatusCode");

                    b.ToTable("Basket", (string)null);
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.BasketProduct", b =>
                {
                    b.Property<Guid>("BasketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("BasketId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("BasketProduct");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.BasketStatus", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("BasketStatus", (string)null);
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Brand", b =>
                {
                    b.Property<Guid>("BrandID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrandLogo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrandID");

                    b.ToTable("Brand", (string)null);
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Category", b =>
                {
                    b.Property<Guid>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<Guid>("ParentCategoryID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoryID");

                    b.HasIndex("ParentCategoryID");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryID = new Guid("a825c26a-dc51-1f8f-27ca-3da2e35eabf7"),
                            CategoryName = "System.String[]",
                            IsFeatured = false,
                            ParentCategoryID = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            CategoryID = new Guid("ba9b08af-e42a-b3df-f584-2e4c6d6cfda4"),
                            CategoryName = "System.String[]",
                            IsFeatured = false,
                            ParentCategoryID = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            CategoryID = new Guid("2eca204c-7f46-85a6-734c-5fcac10767d4"),
                            CategoryName = "System.String[]",
                            IsFeatured = false,
                            ParentCategoryID = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Customer", b =>
                {
                    b.Property<Guid>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customer", (string)null);

                    b.HasData(
                        new
                        {
                            CustomerID = new Guid("bc4bc437-55aa-8b62-8c2b-18e0cd5c9bfc"),
                            BirthDate = new DateTime(2013, 1, 3, 23, 58, 50, 476, DateTimeKind.Local).AddTicks(2664),
                            EmailAddress = "Leo.Erdman@yahoo.com",
                            FirstName = "Leo",
                            LastName = "Erdman",
                            Password = "6696cd5ca33499534cd45b3b847c9c2cf14f4e46",
                            PhoneNumber = "(990) 777-9693"
                        },
                        new
                        {
                            CustomerID = new Guid("45390373-1324-ddf7-6b88-c0d5ce2fca23"),
                            BirthDate = new DateTime(2020, 12, 4, 5, 45, 35, 922, DateTimeKind.Local).AddTicks(4903),
                            EmailAddress = "Jody_Mueller@yahoo.com",
                            FirstName = "Jody",
                            LastName = "Mueller",
                            Password = "c63d3f8335efecea32561e9cad0f9b873fc52744",
                            PhoneNumber = "(424) 328-1046 x95242"
                        },
                        new
                        {
                            CustomerID = new Guid("1b50c483-4054-739d-9eb6-7b1a753e18f3"),
                            BirthDate = new DateTime(2008, 4, 23, 7, 49, 45, 206, DateTimeKind.Local).AddTicks(9074),
                            EmailAddress = "Dave_Emard@hotmail.com",
                            FirstName = "Dave",
                            LastName = "Emard",
                            Password = "983d1c2f4f52fffbcc9d472b83e0d33e717b879e",
                            PhoneNumber = "(911) 666-7233 x17926"
                        },
                        new
                        {
                            CustomerID = new Guid("59b07ad8-4da2-fb4b-1110-d2f0e76ec241"),
                            BirthDate = new DateTime(2020, 12, 8, 10, 57, 28, 97, DateTimeKind.Local).AddTicks(181),
                            EmailAddress = "Willis_Bosco@hotmail.com",
                            FirstName = "Willis",
                            LastName = "Bosco",
                            Password = "24f6902767a4b7ac3ce218a0a47770b03d149e1a",
                            PhoneNumber = "965-631-8349 x7150"
                        },
                        new
                        {
                            CustomerID = new Guid("0c8118a2-d42d-d146-9fab-abac610b2644"),
                            BirthDate = new DateTime(2012, 1, 20, 13, 46, 17, 405, DateTimeKind.Local).AddTicks(7932),
                            EmailAddress = "Jason.Moen@yahoo.com",
                            FirstName = "Jason",
                            LastName = "Moen",
                            Password = "3162614a641ce59e29b9fcb3b890e6fc9942cc76",
                            PhoneNumber = "247-901-4979 x6423"
                        },
                        new
                        {
                            CustomerID = new Guid("5f9e1db4-6ac0-c4e7-79fd-f1e1c6da7a7a"),
                            BirthDate = new DateTime(2020, 12, 21, 8, 24, 2, 459, DateTimeKind.Local).AddTicks(8249),
                            EmailAddress = "Bill_Effertz36@gmail.com",
                            FirstName = "Bill",
                            LastName = "Effertz",
                            Password = "358b1e3621b69cb77cf49cd97aae0d1c531052f9",
                            PhoneNumber = "1-642-502-1850"
                        },
                        new
                        {
                            CustomerID = new Guid("e71c640d-36b4-1771-1522-4146833e0ab4"),
                            BirthDate = new DateTime(2005, 5, 8, 18, 32, 51, 746, DateTimeKind.Local).AddTicks(3176),
                            EmailAddress = "Betty11@hotmail.com",
                            FirstName = "Betty",
                            LastName = "Carroll",
                            Password = "5e199dea95da4fb7db3f11d8963bfc3604b41c7e",
                            PhoneNumber = "(785) 613-0336"
                        },
                        new
                        {
                            CustomerID = new Guid("3d82ce02-caad-45d4-3d2b-060343a42c5b"),
                            BirthDate = new DateTime(2010, 9, 28, 2, 32, 43, 257, DateTimeKind.Local).AddTicks(7689),
                            EmailAddress = "Wesley.Kessler@yahoo.com",
                            FirstName = "Wesley",
                            LastName = "Kessler",
                            Password = "1739d7774fa7914dcc785bd1d83abdb6ef1aa3f4",
                            PhoneNumber = "1-857-452-4961 x3423"
                        },
                        new
                        {
                            CustomerID = new Guid("25f44f6b-6b4d-c33e-b4d7-62c1e3b88180"),
                            BirthDate = new DateTime(2018, 11, 23, 2, 33, 20, 131, DateTimeKind.Local).AddTicks(2581),
                            EmailAddress = "Cecelia71@yahoo.com",
                            FirstName = "Cecelia",
                            LastName = "Kemmer",
                            Password = "12e79e994924ff9801357c984d9ba5e6f627164d",
                            PhoneNumber = "(786) 206-8295 x33976"
                        },
                        new
                        {
                            CustomerID = new Guid("5252bb61-ebac-91f5-956d-b4aaafafdb09"),
                            BirthDate = new DateTime(2008, 1, 18, 0, 37, 23, 68, DateTimeKind.Local).AddTicks(8725),
                            EmailAddress = "Gwen.Mitchell@yahoo.com",
                            FirstName = "Gwen",
                            LastName = "Mitchell",
                            Password = "a4ae1a12fa5127f317e5123c216ddd8d28430865",
                            PhoneNumber = "389-528-5652 x8814"
                        },
                        new
                        {
                            CustomerID = new Guid("d19441e0-72d6-a5bd-de53-4e3e027bfd56"),
                            BirthDate = new DateTime(2012, 12, 22, 2, 2, 50, 932, DateTimeKind.Local).AddTicks(3502),
                            EmailAddress = "Kevin_Bauch@yahoo.com",
                            FirstName = "Kevin",
                            LastName = "Bauch",
                            Password = "78dd4ec7dfffc677b38b9095c7326a4c97ac344b",
                            PhoneNumber = "1-331-573-5161 x2016"
                        },
                        new
                        {
                            CustomerID = new Guid("06226c88-d66d-c73b-71a5-8e3db55da1e3"),
                            BirthDate = new DateTime(2010, 7, 29, 21, 56, 21, 165, DateTimeKind.Local).AddTicks(8829),
                            EmailAddress = "Ella.Tremblay99@gmail.com",
                            FirstName = "Ella",
                            LastName = "Tremblay",
                            Password = "9e19e92979a8f002f8e51a495a605571d0da5ee8",
                            PhoneNumber = "962.979.5213"
                        },
                        new
                        {
                            CustomerID = new Guid("cbcc4709-fb18-4e92-be3f-e4776e1d33d2"),
                            BirthDate = new DateTime(2011, 9, 10, 23, 35, 33, 908, DateTimeKind.Local).AddTicks(59),
                            EmailAddress = "Luke89@yahoo.com",
                            FirstName = "Luke",
                            LastName = "Luettgen",
                            Password = "cb7c609cf9e39835d3e7aa7aa9454c841023d14f",
                            PhoneNumber = "323.293.2489 x80858"
                        },
                        new
                        {
                            CustomerID = new Guid("17109f43-9961-8417-fc39-18a7db0884b9"),
                            BirthDate = new DateTime(2011, 8, 15, 4, 25, 55, 389, DateTimeKind.Local).AddTicks(8124),
                            EmailAddress = "Bernadette_Schneider2@hotmail.com",
                            FirstName = "Bernadette",
                            LastName = "Schneider",
                            Password = "5144c4b954eef3204b7f8acea0817a815733bdfb",
                            PhoneNumber = "254.719.1773 x2397"
                        },
                        new
                        {
                            CustomerID = new Guid("df38650f-ce29-4c95-2e6d-a19b7340b9dc"),
                            BirthDate = new DateTime(2021, 4, 5, 10, 35, 0, 751, DateTimeKind.Local).AddTicks(2069),
                            EmailAddress = "Ebony40@yahoo.com",
                            FirstName = "Ebony",
                            LastName = "Bergnaum",
                            Password = "818624c5be4494432905eed667c85838a535c5d2",
                            PhoneNumber = "1-986-404-1163"
                        },
                        new
                        {
                            CustomerID = new Guid("7ae9f6d0-749d-78c0-f8fb-db34bb7389f3"),
                            BirthDate = new DateTime(2021, 5, 5, 14, 32, 52, 462, DateTimeKind.Local).AddTicks(8895),
                            EmailAddress = "Lee_Veum7@hotmail.com",
                            FirstName = "Lee",
                            LastName = "Veum",
                            Password = "0a207ed38dca752ab4d363e870148d6de73b0bf3",
                            PhoneNumber = "711-377-2040"
                        },
                        new
                        {
                            CustomerID = new Guid("2837f375-cb6b-89aa-8a99-b1e3177c1fc2"),
                            BirthDate = new DateTime(2005, 7, 6, 15, 19, 44, 193, DateTimeKind.Local).AddTicks(4261),
                            EmailAddress = "Max.Koch57@yahoo.com",
                            FirstName = "Max",
                            LastName = "Koch",
                            Password = "8f2ecec7dad223befcb1e9f6724da32bdd1090be",
                            PhoneNumber = "1-770-593-3072 x2628"
                        },
                        new
                        {
                            CustomerID = new Guid("02de17d4-6f81-7b42-c462-a57575bbe608"),
                            BirthDate = new DateTime(2009, 12, 13, 7, 51, 36, 559, DateTimeKind.Local).AddTicks(2279),
                            EmailAddress = "Lula_Brown63@hotmail.com",
                            FirstName = "Lula",
                            LastName = "Brown",
                            Password = "b2c6aa4d54c6cef5e4bf9ccb6819e1a9dfc77691",
                            PhoneNumber = "871.533.5356 x019"
                        },
                        new
                        {
                            CustomerID = new Guid("e385b60f-9bb7-6e04-28da-f5794b87077e"),
                            BirthDate = new DateTime(2019, 5, 26, 23, 24, 58, 547, DateTimeKind.Local).AddTicks(2368),
                            EmailAddress = "Dorothy.Monahan24@yahoo.com",
                            FirstName = "Dorothy",
                            LastName = "Monahan",
                            Password = "a1d26d62c5c7aa68616e7dcb9a68e639ef1e26ab",
                            PhoneNumber = "595.926.7122"
                        },
                        new
                        {
                            CustomerID = new Guid("6bb6c4f8-0ecf-206a-81e4-a31a1ec334e1"),
                            BirthDate = new DateTime(2021, 7, 14, 0, 49, 4, 237, DateTimeKind.Local).AddTicks(975),
                            EmailAddress = "Gustavo4@hotmail.com",
                            FirstName = "Gustavo",
                            LastName = "Hodkiewicz",
                            Password = "1f48b70e9028591e05cf4854a80bd9d7f0bcd278",
                            PhoneNumber = "534-270-0322 x0989"
                        },
                        new
                        {
                            CustomerID = new Guid("4e9e0416-5dcc-eaaf-e4ea-f564653c840e"),
                            BirthDate = new DateTime(2010, 6, 21, 14, 54, 41, 756, DateTimeKind.Local).AddTicks(3047),
                            EmailAddress = "Agnes.Grady51@gmail.com",
                            FirstName = "Agnes",
                            LastName = "Grady",
                            Password = "c450ce99b7d5d7dd96188c4611d7d108aed63ccd",
                            PhoneNumber = "(629) 840-0971"
                        },
                        new
                        {
                            CustomerID = new Guid("4f3ea6b4-5f51-a64e-dddb-25b7075f7a1a"),
                            BirthDate = new DateTime(2009, 5, 1, 11, 36, 17, 92, DateTimeKind.Local).AddTicks(3788),
                            EmailAddress = "Karla75@gmail.com",
                            FirstName = "Karla",
                            LastName = "Labadie",
                            Password = "d0ef90042089056e33e1e6f56c2ac1ef8be0c1c9",
                            PhoneNumber = "374-462-0766"
                        },
                        new
                        {
                            CustomerID = new Guid("508de087-eab6-cd66-3024-4ed6af3e7c96"),
                            BirthDate = new DateTime(2007, 1, 30, 4, 18, 30, 982, DateTimeKind.Local).AddTicks(7686),
                            EmailAddress = "Penny53@hotmail.com",
                            FirstName = "Penny",
                            LastName = "Maggio",
                            Password = "5d5d6305bdec8383bf6b8f27e016a12dbf13fbe9",
                            PhoneNumber = "621-489-5079"
                        },
                        new
                        {
                            CustomerID = new Guid("6592ffa4-9582-f7d3-e5ee-11b3f21aa4c9"),
                            BirthDate = new DateTime(2010, 3, 1, 7, 59, 41, 989, DateTimeKind.Local).AddTicks(7959),
                            EmailAddress = "Bessie.Stark34@yahoo.com",
                            FirstName = "Bessie",
                            LastName = "Stark",
                            Password = "147334a96edad735e6ef32f9bf88d960a826dbdc",
                            PhoneNumber = "627-497-3899 x58330"
                        },
                        new
                        {
                            CustomerID = new Guid("83e031c8-dd84-e831-4e3e-69bb8b267696"),
                            BirthDate = new DateTime(2013, 2, 14, 10, 42, 2, 328, DateTimeKind.Local).AddTicks(3418),
                            EmailAddress = "Genevieve.Beatty50@hotmail.com",
                            FirstName = "Genevieve",
                            LastName = "Beatty",
                            Password = "edfbc8bc179d2caeaaa932f5ccab60b0a01eee34",
                            PhoneNumber = "1-773-960-6793 x9063"
                        },
                        new
                        {
                            CustomerID = new Guid("8a8979d5-cbe9-b414-c8f1-583a95f521d2"),
                            BirthDate = new DateTime(2008, 4, 17, 4, 4, 9, 407, DateTimeKind.Local).AddTicks(9948),
                            EmailAddress = "Jonathan.Halvorson8@hotmail.com",
                            FirstName = "Jonathan",
                            LastName = "Halvorson",
                            Password = "1aacb1fc7328dfaf594ddf7edcafcdc3b3b794c4",
                            PhoneNumber = "619-224-1555"
                        },
                        new
                        {
                            CustomerID = new Guid("9485a118-95b8-8dc6-b9d2-d01778da3ba3"),
                            BirthDate = new DateTime(2010, 3, 14, 0, 52, 52, 699, DateTimeKind.Local).AddTicks(9295),
                            EmailAddress = "Delbert74@hotmail.com",
                            FirstName = "Delbert",
                            LastName = "Renner",
                            Password = "39decd5fa7857b97d26aa43492ba3139921ead43",
                            PhoneNumber = "630-648-0666 x221"
                        },
                        new
                        {
                            CustomerID = new Guid("ad53a40c-fd81-737c-2baa-179ca4555b3c"),
                            BirthDate = new DateTime(2009, 5, 31, 3, 15, 17, 138, DateTimeKind.Local).AddTicks(2712),
                            EmailAddress = "Kim.Cremin@yahoo.com",
                            FirstName = "Kim",
                            LastName = "Cremin",
                            Password = "8a21dbbece0db960a581cf77fe754e975e299352",
                            PhoneNumber = "1-921-624-6620 x3924"
                        },
                        new
                        {
                            CustomerID = new Guid("04a655d7-65df-fb84-4919-507d083470c0"),
                            BirthDate = new DateTime(2011, 4, 25, 10, 56, 5, 860, DateTimeKind.Local).AddTicks(826),
                            EmailAddress = "Joel.Toy92@yahoo.com",
                            FirstName = "Joel",
                            LastName = "Toy",
                            Password = "197d5179a4e98de4e93d858e908a152eb0579f90",
                            PhoneNumber = "1-238-649-1124 x59417"
                        },
                        new
                        {
                            CustomerID = new Guid("1df4b05e-34ba-84fb-5116-ddec6ef1dcb8"),
                            BirthDate = new DateTime(2007, 7, 2, 0, 43, 56, 405, DateTimeKind.Local).AddTicks(4313),
                            EmailAddress = "Hubert81@yahoo.com",
                            FirstName = "Hubert",
                            LastName = "VonRueden",
                            Password = "b8100af888e0a017f4090a3704872b9ee59d3967",
                            PhoneNumber = "845-510-2653"
                        },
                        new
                        {
                            CustomerID = new Guid("3de3c8e0-047c-ca07-d289-cf179114c8c5"),
                            BirthDate = new DateTime(2012, 8, 10, 3, 16, 2, 332, DateTimeKind.Local).AddTicks(1914),
                            EmailAddress = "Terry.Boyle@yahoo.com",
                            FirstName = "Terry",
                            LastName = "Boyle",
                            Password = "6a089f00322a26015023cb410e715a6d8ce4864f",
                            PhoneNumber = "926.247.0821 x5290"
                        },
                        new
                        {
                            CustomerID = new Guid("b26eefbe-0062-a41e-25eb-7991a8a088b5"),
                            BirthDate = new DateTime(2012, 1, 9, 5, 22, 58, 73, DateTimeKind.Local).AddTicks(890),
                            EmailAddress = "Mamie5@gmail.com",
                            FirstName = "Mamie",
                            LastName = "Dietrich",
                            Password = "dc1562e3c2b2000effa24b0258eefb98613246ba",
                            PhoneNumber = "1-775-380-0056 x892"
                        },
                        new
                        {
                            CustomerID = new Guid("229abf9b-25e9-3504-0742-21d5d81dbf2f"),
                            BirthDate = new DateTime(2012, 9, 5, 13, 42, 41, 831, DateTimeKind.Local).AddTicks(7112),
                            EmailAddress = "Lloyd.Hamill92@yahoo.com",
                            FirstName = "Lloyd",
                            LastName = "Hamill",
                            Password = "b1a7dd6230129c4b3d32358c582cc853d39a3131",
                            PhoneNumber = "1-829-277-9179"
                        },
                        new
                        {
                            CustomerID = new Guid("a5bdf4d6-90b1-23c2-06b0-5bd772d0abb5"),
                            BirthDate = new DateTime(2021, 12, 17, 14, 44, 42, 102, DateTimeKind.Local).AddTicks(6020),
                            EmailAddress = "Israel74@yahoo.com",
                            FirstName = "Israel",
                            LastName = "Deckow",
                            Password = "508559f33acafe8546ec3299613b182837c31cb8",
                            PhoneNumber = "1-773-524-0594 x502"
                        },
                        new
                        {
                            CustomerID = new Guid("cbd535a9-1a80-0ba8-c153-5a2e84f9f7de"),
                            BirthDate = new DateTime(2008, 5, 26, 12, 45, 33, 782, DateTimeKind.Local).AddTicks(5327),
                            EmailAddress = "Lela_Smitham10@gmail.com",
                            FirstName = "Lela",
                            LastName = "Smitham",
                            Password = "ec028d9864a0d0c3251fab9dbea9c43d90dd4dec",
                            PhoneNumber = "1-980-532-9383"
                        },
                        new
                        {
                            CustomerID = new Guid("dbb4dee9-5dcf-9328-d65a-c756511704cd"),
                            BirthDate = new DateTime(2009, 4, 15, 2, 26, 55, 701, DateTimeKind.Local).AddTicks(8626),
                            EmailAddress = "Louise.Schinner@gmail.com",
                            FirstName = "Louise",
                            LastName = "Schinner",
                            Password = "b1038b8c873fd877d0570adb0bb131f6107ae8b3",
                            PhoneNumber = "(614) 301-3537"
                        },
                        new
                        {
                            CustomerID = new Guid("a9fade29-defb-def1-7af0-0972a708ecee"),
                            BirthDate = new DateTime(2018, 1, 8, 3, 27, 50, 741, DateTimeKind.Local).AddTicks(8615),
                            EmailAddress = "Bernadette40@yahoo.com",
                            FirstName = "Bernadette",
                            LastName = "Boyle",
                            Password = "6221dd1fd6def571d6368833a696e69742c3d220",
                            PhoneNumber = "640.543.4842"
                        },
                        new
                        {
                            CustomerID = new Guid("6cf24796-c5a3-36cf-efcb-1060857f7dce"),
                            BirthDate = new DateTime(2013, 2, 14, 3, 57, 9, 384, DateTimeKind.Local).AddTicks(6628),
                            EmailAddress = "Ray13@yahoo.com",
                            FirstName = "Ray",
                            LastName = "Robel",
                            Password = "27a29c745c52899edd01d99db102d08058f69d7e",
                            PhoneNumber = "(815) 213-1167"
                        },
                        new
                        {
                            CustomerID = new Guid("df9fb879-69ea-6a80-a1bc-0dd90ae51595"),
                            BirthDate = new DateTime(2016, 7, 31, 14, 26, 57, 961, DateTimeKind.Local).AddTicks(4881),
                            EmailAddress = "Damon.Rogahn@gmail.com",
                            FirstName = "Damon",
                            LastName = "Rogahn",
                            Password = "c152f1a9e545adcc52ed2f1e0a06586b05e4f3df",
                            PhoneNumber = "958.703.1093 x14990"
                        },
                        new
                        {
                            CustomerID = new Guid("26282fa9-92b6-e633-52ae-1cf10cc1f9d2"),
                            BirthDate = new DateTime(2018, 8, 21, 0, 17, 33, 48, DateTimeKind.Local).AddTicks(2412),
                            EmailAddress = "Dewey.Howell@yahoo.com",
                            FirstName = "Dewey",
                            LastName = "Howell",
                            Password = "6b65823243d566f8ab0899cb496ae0ed4344a558",
                            PhoneNumber = "506.504.3438"
                        },
                        new
                        {
                            CustomerID = new Guid("600b1c2e-50d1-2994-3e82-e8f32a0690d7"),
                            BirthDate = new DateTime(2015, 5, 19, 15, 35, 28, 657, DateTimeKind.Local).AddTicks(6625),
                            EmailAddress = "Olivia56@gmail.com",
                            FirstName = "Olivia",
                            LastName = "Cummings",
                            Password = "ed77f296d7a62bbe483c6e9c1ddbb9d7e84eaade",
                            PhoneNumber = "500.869.4335"
                        },
                        new
                        {
                            CustomerID = new Guid("c99faa7a-7cf4-63ef-ffc2-cbae2e49fb5e"),
                            BirthDate = new DateTime(2016, 10, 27, 21, 39, 6, 583, DateTimeKind.Local).AddTicks(6152),
                            EmailAddress = "Stella_Veum4@gmail.com",
                            FirstName = "Stella",
                            LastName = "Veum",
                            Password = "b7599e4fa2472f9c5dd4f96259ae997791e8e0bd",
                            PhoneNumber = "829.353.3532"
                        },
                        new
                        {
                            CustomerID = new Guid("515470bf-01c1-72e9-c6e8-69be5ca69965"),
                            BirthDate = new DateTime(2019, 11, 11, 0, 26, 11, 203, DateTimeKind.Local).AddTicks(7364),
                            EmailAddress = "Mathew_Wiegand82@yahoo.com",
                            FirstName = "Mathew",
                            LastName = "Wiegand",
                            Password = "35fa9a13a5966edd05f6ec107ed3172bbf9058ef",
                            PhoneNumber = "704-334-2785"
                        },
                        new
                        {
                            CustomerID = new Guid("85eb59e6-7ca5-81f3-caf5-f024eda79d7e"),
                            BirthDate = new DateTime(2012, 11, 18, 20, 15, 25, 116, DateTimeKind.Local).AddTicks(6966),
                            EmailAddress = "Leroy20@hotmail.com",
                            FirstName = "Leroy",
                            LastName = "Dicki",
                            Password = "a23f757ecf7db3289359cb6276979e56c32c9c62",
                            PhoneNumber = "423.288.3543"
                        },
                        new
                        {
                            CustomerID = new Guid("fa3ed639-6cd8-cde8-661e-558592b894e9"),
                            BirthDate = new DateTime(2022, 2, 12, 8, 27, 38, 284, DateTimeKind.Local).AddTicks(8191),
                            EmailAddress = "Sylvester.Barrows67@yahoo.com",
                            FirstName = "Sylvester",
                            LastName = "Barrows",
                            Password = "c452385f44122d41e517ec8cc3ab3dd5cdefd1a2",
                            PhoneNumber = "418-419-3076 x7227"
                        },
                        new
                        {
                            CustomerID = new Guid("b5717ef0-ecfb-e7c2-0039-5e4cc8ec96bd"),
                            BirthDate = new DateTime(2019, 3, 24, 5, 26, 10, 481, DateTimeKind.Local).AddTicks(5109),
                            EmailAddress = "Rolando_Ratke38@gmail.com",
                            FirstName = "Rolando",
                            LastName = "Ratke",
                            Password = "a46104d04b419e56348e2b9e4e13d3b28e443f3b",
                            PhoneNumber = "1-315-411-8407"
                        },
                        new
                        {
                            CustomerID = new Guid("dbf5e900-8387-a592-66d6-49adbe48af83"),
                            BirthDate = new DateTime(2016, 6, 23, 15, 33, 9, 46, DateTimeKind.Local).AddTicks(1605),
                            EmailAddress = "Cecilia.Okuneva@yahoo.com",
                            FirstName = "Cecilia",
                            LastName = "Okuneva",
                            Password = "ac3755aedb138a9318ab1095447b0a36b94a38ab",
                            PhoneNumber = "(438) 419-7689"
                        },
                        new
                        {
                            CustomerID = new Guid("389dd9c2-cc3c-c553-e335-8b4fbc1e6dd8"),
                            BirthDate = new DateTime(2014, 1, 5, 20, 39, 48, 492, DateTimeKind.Local).AddTicks(4164),
                            EmailAddress = "Alejandro.Haley61@gmail.com",
                            FirstName = "Alejandro",
                            LastName = "Haley",
                            Password = "4e7389b1e6388bb796c1db47413d5b55e450f6bd",
                            PhoneNumber = "1-673-222-9441"
                        },
                        new
                        {
                            CustomerID = new Guid("2c1f529b-992f-9830-836e-6f8a642108a7"),
                            BirthDate = new DateTime(2015, 2, 16, 0, 49, 47, 744, DateTimeKind.Local).AddTicks(422),
                            EmailAddress = "Darryl.Deckow@yahoo.com",
                            FirstName = "Darryl",
                            LastName = "Deckow",
                            Password = "a9af7e4e748d4c23962b3e61076cee66f5afc1ab",
                            PhoneNumber = "964.702.2613"
                        },
                        new
                        {
                            CustomerID = new Guid("198b6824-2370-7aee-3997-f07ca9692dfd"),
                            BirthDate = new DateTime(2014, 9, 26, 23, 1, 1, 665, DateTimeKind.Local).AddTicks(6577),
                            EmailAddress = "Gwen.Stanton@hotmail.com",
                            FirstName = "Gwen",
                            LastName = "Stanton",
                            Password = "66bc501a4c4282567380cdd9f98f705db9cd5d2f",
                            PhoneNumber = "216-716-4654"
                        },
                        new
                        {
                            CustomerID = new Guid("e631c0a4-2a4b-e936-886a-fb966aaa326e"),
                            BirthDate = new DateTime(2019, 9, 28, 9, 38, 37, 206, DateTimeKind.Local).AddTicks(8895),
                            EmailAddress = "Becky.Wuckert95@yahoo.com",
                            FirstName = "Becky",
                            LastName = "Wuckert",
                            Password = "3029ca80e769651864293da1fb26d74409d62595",
                            PhoneNumber = "513-782-2233 x4444"
                        },
                        new
                        {
                            CustomerID = new Guid("500675fb-7f19-246f-c025-c2e1a4ce0c85"),
                            BirthDate = new DateTime(2016, 5, 10, 11, 8, 48, 419, DateTimeKind.Local).AddTicks(40),
                            EmailAddress = "Michelle_Stokes@hotmail.com",
                            FirstName = "Michelle",
                            LastName = "Stokes",
                            Password = "08b7bba1f0af843a0eb465e50a76a4eb8ae47c43",
                            PhoneNumber = "(474) 466-9343 x0807"
                        },
                        new
                        {
                            CustomerID = new Guid("26d855eb-aeaf-596e-3604-8a7350ff8d9b"),
                            BirthDate = new DateTime(2020, 9, 6, 5, 49, 33, 688, DateTimeKind.Local).AddTicks(5075),
                            EmailAddress = "Carl58@gmail.com",
                            FirstName = "Carl",
                            LastName = "Jacobs",
                            Password = "60be40ce571d2f8cf20d487f2cc8852c9f834ce8",
                            PhoneNumber = "276.247.3020 x706"
                        },
                        new
                        {
                            CustomerID = new Guid("f6e62421-573b-7e52-eb61-0e42f8525d73"),
                            BirthDate = new DateTime(2013, 3, 17, 0, 41, 49, 942, DateTimeKind.Local).AddTicks(9335),
                            EmailAddress = "Jeannette11@gmail.com",
                            FirstName = "Jeannette",
                            LastName = "Gibson",
                            Password = "d57ac23121eb69872474f2784ca4c52011fa3e26",
                            PhoneNumber = "233.734.9333 x532"
                        },
                        new
                        {
                            CustomerID = new Guid("536e3b06-bcf1-9f9b-a3d1-85f21ace8a5c"),
                            BirthDate = new DateTime(2013, 5, 8, 21, 5, 42, 436, DateTimeKind.Local).AddTicks(4807),
                            EmailAddress = "Joan.Haley@gmail.com",
                            FirstName = "Joan",
                            LastName = "Haley",
                            Password = "5da6cbda9e5f5d6474e1b9cd00c3e204d73b7700",
                            PhoneNumber = "773.393.8364"
                        },
                        new
                        {
                            CustomerID = new Guid("0b216413-796e-d10b-38c6-61605ef423df"),
                            BirthDate = new DateTime(2005, 7, 10, 8, 58, 29, 25, DateTimeKind.Local).AddTicks(7632),
                            EmailAddress = "Bruce85@yahoo.com",
                            FirstName = "Bruce",
                            LastName = "Goyette",
                            Password = "12ddaec7cfbddf97f33cb2f76861aec30acad741",
                            PhoneNumber = "(587) 555-4184"
                        },
                        new
                        {
                            CustomerID = new Guid("d0bcf422-3628-e72f-9351-e8b379128887"),
                            BirthDate = new DateTime(2011, 3, 19, 2, 47, 21, 655, DateTimeKind.Local).AddTicks(3386),
                            EmailAddress = "Deanna.Stamm@hotmail.com",
                            FirstName = "Deanna",
                            LastName = "Stamm",
                            Password = "6e1ddc14bb43b9468cb55dad9645a03033588283",
                            PhoneNumber = "608-455-9087 x9648"
                        },
                        new
                        {
                            CustomerID = new Guid("1a6ba1f2-f341-2775-0b48-1747452d4301"),
                            BirthDate = new DateTime(2020, 7, 18, 16, 17, 57, 240, DateTimeKind.Local).AddTicks(5214),
                            EmailAddress = "Lynda_Douglas87@yahoo.com",
                            FirstName = "Lynda",
                            LastName = "Douglas",
                            Password = "eeaf7583a2410f2e1acf9dc81d887c6be750a3ab",
                            PhoneNumber = "(610) 346-4390"
                        },
                        new
                        {
                            CustomerID = new Guid("c4db5247-873b-a367-a696-4e3381d554fb"),
                            BirthDate = new DateTime(2021, 7, 11, 4, 2, 41, 425, DateTimeKind.Local).AddTicks(7844),
                            EmailAddress = "Cornelius_Fritsch@gmail.com",
                            FirstName = "Cornelius",
                            LastName = "Fritsch",
                            Password = "39c1fc4e7b5da570acade9281feb21dafb7cac48",
                            PhoneNumber = "(728) 643-9623"
                        },
                        new
                        {
                            CustomerID = new Guid("f3abb846-e323-701f-d0d4-71f618b7e13c"),
                            BirthDate = new DateTime(2022, 3, 19, 12, 3, 0, 835, DateTimeKind.Local).AddTicks(9913),
                            EmailAddress = "Tim.Beatty0@gmail.com",
                            FirstName = "Tim",
                            LastName = "Beatty",
                            Password = "7171a32feeddc100c3b45d9495a3e2b1bb582bbc",
                            PhoneNumber = "(626) 832-4082 x12227"
                        },
                        new
                        {
                            CustomerID = new Guid("112a324a-5037-1c70-7661-d3f2bc239249"),
                            BirthDate = new DateTime(2021, 12, 23, 18, 12, 45, 788, DateTimeKind.Local).AddTicks(8818),
                            EmailAddress = "Lynda.Zemlak52@yahoo.com",
                            FirstName = "Lynda",
                            LastName = "Zemlak",
                            Password = "4e26e95ef1f1e959e2c341e3b760c854164a6dca",
                            PhoneNumber = "1-594-335-0994 x39038"
                        },
                        new
                        {
                            CustomerID = new Guid("3e46080f-82e9-307c-2fe7-3be6e061cb0a"),
                            BirthDate = new DateTime(2017, 2, 27, 5, 38, 38, 277, DateTimeKind.Local).AddTicks(5651),
                            EmailAddress = "Michael_Schmitt@yahoo.com",
                            FirstName = "Michael",
                            LastName = "Schmitt",
                            Password = "675e6595c8f96127b06370d31bd6aacf0e8c8de4",
                            PhoneNumber = "255.449.1947 x2795"
                        },
                        new
                        {
                            CustomerID = new Guid("e9dc3518-cf04-8aba-2a25-2a3d8d41346d"),
                            BirthDate = new DateTime(2012, 10, 23, 4, 56, 35, 816, DateTimeKind.Local).AddTicks(2256),
                            EmailAddress = "Kim_Medhurst38@hotmail.com",
                            FirstName = "Kim",
                            LastName = "Medhurst",
                            Password = "2f46e6563ebab651513afa7cfc46939e582b8d38",
                            PhoneNumber = "(261) 265-4344"
                        },
                        new
                        {
                            CustomerID = new Guid("7fa6a726-e3ae-b21a-479b-a9f72918574f"),
                            BirthDate = new DateTime(2010, 8, 5, 8, 47, 20, 219, DateTimeKind.Local).AddTicks(8550),
                            EmailAddress = "Eduardo.Trantow4@gmail.com",
                            FirstName = "Eduardo",
                            LastName = "Trantow",
                            Password = "d164ad13d25600e4dceec3212ebf1d8795711795",
                            PhoneNumber = "466.781.3188"
                        },
                        new
                        {
                            CustomerID = new Guid("a12ac9a0-4edb-9179-578e-1ad141fdb19a"),
                            BirthDate = new DateTime(2020, 12, 1, 7, 33, 0, 96, DateTimeKind.Local).AddTicks(6282),
                            EmailAddress = "Clifford.Hirthe@hotmail.com",
                            FirstName = "Clifford",
                            LastName = "Hirthe",
                            Password = "276a322b048ce37cb8606ac45e645c45dd685748",
                            PhoneNumber = "1-453-571-4931 x15580"
                        },
                        new
                        {
                            CustomerID = new Guid("78b97b97-1796-c86c-5ad4-57f7ac31302f"),
                            BirthDate = new DateTime(2008, 12, 2, 22, 4, 27, 822, DateTimeKind.Local).AddTicks(8135),
                            EmailAddress = "Floyd.Harris52@hotmail.com",
                            FirstName = "Floyd",
                            LastName = "Harris",
                            Password = "d30c8e295c4d854f9cc4f47ef21649f0fdeb2ba6",
                            PhoneNumber = "1-624-432-6348 x44889"
                        },
                        new
                        {
                            CustomerID = new Guid("c6c40add-8950-d07c-8035-85a24a774bbd"),
                            BirthDate = new DateTime(2009, 1, 25, 7, 15, 16, 840, DateTimeKind.Local).AddTicks(275),
                            EmailAddress = "Rosie74@gmail.com",
                            FirstName = "Rosie",
                            LastName = "Gottlieb",
                            Password = "a530852e57cf06dd7f35907298452085f44f98f3",
                            PhoneNumber = "903.623.5171"
                        },
                        new
                        {
                            CustomerID = new Guid("692368b1-47d7-6322-70e2-d6fd0d46bdb2"),
                            BirthDate = new DateTime(2019, 3, 10, 19, 35, 7, 142, DateTimeKind.Local).AddTicks(5318),
                            EmailAddress = "Al_Schmidt@yahoo.com",
                            FirstName = "Al",
                            LastName = "Schmidt",
                            Password = "25869e79f20b2b7a344f9b9e5fe64bce248c7a11",
                            PhoneNumber = "1-571-463-2230"
                        },
                        new
                        {
                            CustomerID = new Guid("ba53d8e6-5d79-a4c4-155e-aba5f151b659"),
                            BirthDate = new DateTime(2005, 2, 15, 5, 25, 42, 625, DateTimeKind.Local).AddTicks(2870),
                            EmailAddress = "Steven94@yahoo.com",
                            FirstName = "Steven",
                            LastName = "Rempel",
                            Password = "21c5ed813abae2ffad70b24a72f330f80c292023",
                            PhoneNumber = "(618) 666-4879 x688"
                        },
                        new
                        {
                            CustomerID = new Guid("87fb0313-c4e6-ae65-f72f-e949511a21b2"),
                            BirthDate = new DateTime(2012, 11, 27, 2, 30, 55, 298, DateTimeKind.Local).AddTicks(1988),
                            EmailAddress = "Stella5@hotmail.com",
                            FirstName = "Stella",
                            LastName = "Kuvalis",
                            Password = "d959e2a25896b1e67cf397edd02c358cf04dfa1d",
                            PhoneNumber = "851-988-1444"
                        },
                        new
                        {
                            CustomerID = new Guid("93f1478c-50ac-ff0b-8fbf-fc1b8277c496"),
                            BirthDate = new DateTime(2010, 12, 16, 21, 29, 31, 986, DateTimeKind.Local).AddTicks(2272),
                            EmailAddress = "Amelia.Hayes@gmail.com",
                            FirstName = "Amelia",
                            LastName = "Hayes",
                            Password = "0d67dd3607d016baf0ae0a4584c42b264ec0f2c3",
                            PhoneNumber = "(462) 463-3764 x6178"
                        },
                        new
                        {
                            CustomerID = new Guid("f5a65cc2-e0b4-9241-95be-679d44c02e6d"),
                            BirthDate = new DateTime(2008, 9, 13, 3, 18, 0, 968, DateTimeKind.Local).AddTicks(5057),
                            EmailAddress = "Arturo_Hermann57@hotmail.com",
                            FirstName = "Arturo",
                            LastName = "Hermann",
                            Password = "2be88aef4bee4d9b6a3d8f65af8b4094e559437b",
                            PhoneNumber = "1-976-567-4057"
                        },
                        new
                        {
                            CustomerID = new Guid("cde74099-fcfc-8fb7-2840-5935e2f5f8f0"),
                            BirthDate = new DateTime(2007, 3, 28, 4, 15, 38, 619, DateTimeKind.Local).AddTicks(199),
                            EmailAddress = "Hope73@yahoo.com",
                            FirstName = "Hope",
                            LastName = "Cummerata",
                            Password = "bfe4c1e21ac82170fc72de3180e47f923fdbf2bb",
                            PhoneNumber = "1-553-407-4508"
                        },
                        new
                        {
                            CustomerID = new Guid("f3747a63-d233-29be-5f35-8cd3f4618339"),
                            BirthDate = new DateTime(2018, 8, 14, 7, 2, 0, 106, DateTimeKind.Local).AddTicks(2787),
                            EmailAddress = "Lawrence_Cummerata@gmail.com",
                            FirstName = "Lawrence",
                            LastName = "Cummerata",
                            Password = "22f248bcb3774f3a932c422f1a220ffb699833a1",
                            PhoneNumber = "1-778-399-3332 x41925"
                        },
                        new
                        {
                            CustomerID = new Guid("aa100e0b-ce46-c414-e1d0-61ef71ce9f3f"),
                            BirthDate = new DateTime(2017, 8, 25, 11, 56, 22, 768, DateTimeKind.Local).AddTicks(1365),
                            EmailAddress = "Roberta_Heathcote32@gmail.com",
                            FirstName = "Roberta",
                            LastName = "Heathcote",
                            Password = "1855ded151b8ade5c02b68fe55037aed315176ae",
                            PhoneNumber = "821.766.8022 x0778"
                        },
                        new
                        {
                            CustomerID = new Guid("183ea680-678f-81bc-93f7-bd52e1358c2b"),
                            BirthDate = new DateTime(2018, 1, 25, 6, 58, 31, 481, DateTimeKind.Local).AddTicks(3146),
                            EmailAddress = "Charlotte.Schiller76@yahoo.com",
                            FirstName = "Charlotte",
                            LastName = "Schiller",
                            Password = "81df1daef1267712e7323af224c42a6eabf97c7c",
                            PhoneNumber = "1-912-220-1677 x3986"
                        },
                        new
                        {
                            CustomerID = new Guid("c575c606-a34e-fd44-7e82-af826ac81c9f"),
                            BirthDate = new DateTime(2022, 8, 6, 11, 35, 41, 833, DateTimeKind.Local).AddTicks(4776),
                            EmailAddress = "Melissa.Murphy19@gmail.com",
                            FirstName = "Melissa",
                            LastName = "Murphy",
                            Password = "3e36f56340eac144197b34d457eee1ebea75eb36",
                            PhoneNumber = "278-710-3919 x5763"
                        },
                        new
                        {
                            CustomerID = new Guid("96b8ed26-d1aa-6c09-e3bc-301d54567d82"),
                            BirthDate = new DateTime(2017, 11, 23, 1, 17, 34, 164, DateTimeKind.Local).AddTicks(3259),
                            EmailAddress = "Diane.Morissette@yahoo.com",
                            FirstName = "Diane",
                            LastName = "Morissette",
                            Password = "502d91e53517b1d711ec356d04f783827ad033f9",
                            PhoneNumber = "933-465-4014"
                        },
                        new
                        {
                            CustomerID = new Guid("2f9101d8-c2ff-4ba2-ba99-2c16c807b576"),
                            BirthDate = new DateTime(2013, 10, 4, 14, 0, 58, 649, DateTimeKind.Local).AddTicks(7064),
                            EmailAddress = "Frances.Kilback45@gmail.com",
                            FirstName = "Frances",
                            LastName = "Kilback",
                            Password = "537ef5ccd0db8f9743ee464b5ba765c2778f6db0",
                            PhoneNumber = "1-931-219-6153"
                        },
                        new
                        {
                            CustomerID = new Guid("a55269bb-3263-14b3-14bf-a68a747f8c3d"),
                            BirthDate = new DateTime(2017, 1, 16, 18, 6, 18, 343, DateTimeKind.Local).AddTicks(5886),
                            EmailAddress = "Rochelle25@gmail.com",
                            FirstName = "Rochelle",
                            LastName = "Bogan",
                            Password = "32a7c86092c186751506d18b0a79a07bb62f6b7f",
                            PhoneNumber = "1-509-757-8224"
                        },
                        new
                        {
                            CustomerID = new Guid("7bf6490b-813e-49eb-7e82-7e6024043deb"),
                            BirthDate = new DateTime(2011, 5, 30, 7, 37, 38, 972, DateTimeKind.Local).AddTicks(9897),
                            EmailAddress = "Leslie_Mills79@gmail.com",
                            FirstName = "Leslie",
                            LastName = "Mills",
                            Password = "0273c3609bd9f678b2a8a765ade9b24156b63f99",
                            PhoneNumber = "1-422-618-8837 x46754"
                        },
                        new
                        {
                            CustomerID = new Guid("b56e658d-4598-d556-2dac-578d3b49ae4f"),
                            BirthDate = new DateTime(2005, 4, 26, 0, 32, 24, 953, DateTimeKind.Local).AddTicks(3293),
                            EmailAddress = "Lula.Hammes@gmail.com",
                            FirstName = "Lula",
                            LastName = "Hammes",
                            Password = "0cc6a7c90316a16438e055809e9b8c053ca55732",
                            PhoneNumber = "291-236-6065"
                        },
                        new
                        {
                            CustomerID = new Guid("bc472b35-582e-fc63-dbe0-f3598871e189"),
                            BirthDate = new DateTime(2015, 12, 25, 9, 40, 3, 850, DateTimeKind.Local).AddTicks(5016),
                            EmailAddress = "Wilbert95@hotmail.com",
                            FirstName = "Wilbert",
                            LastName = "Wisoky",
                            Password = "7e6eed1d9c042074dae3fde6f63467360b59e289",
                            PhoneNumber = "(517) 445-1446"
                        },
                        new
                        {
                            CustomerID = new Guid("e0cc2552-7d05-0481-e223-37e03bfc9b3d"),
                            BirthDate = new DateTime(2014, 8, 26, 5, 44, 28, 277, DateTimeKind.Local).AddTicks(1133),
                            EmailAddress = "Otis95@gmail.com",
                            FirstName = "Otis",
                            LastName = "Nicolas",
                            Password = "f409cbc2551d26483a7b6def8339c44c529903ca",
                            PhoneNumber = "714-699-0424"
                        },
                        new
                        {
                            CustomerID = new Guid("47cfe6a8-6c23-bbb7-c082-64c55631d04b"),
                            BirthDate = new DateTime(2005, 11, 12, 6, 51, 21, 321, DateTimeKind.Local).AddTicks(7840),
                            EmailAddress = "Roberto.Romaguera@gmail.com",
                            FirstName = "Roberto",
                            LastName = "Romaguera",
                            Password = "ebdb0ecd6cb8f3ef644579073a89043856095d53",
                            PhoneNumber = "740.222.3759"
                        },
                        new
                        {
                            CustomerID = new Guid("a1bd737e-1d28-920e-5b11-692f3a17da32"),
                            BirthDate = new DateTime(2015, 9, 14, 1, 14, 19, 228, DateTimeKind.Local).AddTicks(2594),
                            EmailAddress = "Lena_Rosenbaum95@hotmail.com",
                            FirstName = "Lena",
                            LastName = "Rosenbaum",
                            Password = "2fae416f79d5e1bd4fbe2be87112059013030378",
                            PhoneNumber = "673.734.5409"
                        },
                        new
                        {
                            CustomerID = new Guid("91825a1c-3110-e286-0b5f-9beddfc43c1d"),
                            BirthDate = new DateTime(2008, 12, 10, 23, 32, 38, 158, DateTimeKind.Local).AddTicks(1562),
                            EmailAddress = "Johnnie_Klein28@hotmail.com",
                            FirstName = "Johnnie",
                            LastName = "Klein",
                            Password = "56b88daf1dcd386baa509d7a43f043fecc018e11",
                            PhoneNumber = "(565) 884-5733 x737"
                        },
                        new
                        {
                            CustomerID = new Guid("035e7866-3aa7-1652-135d-e01887f92c05"),
                            BirthDate = new DateTime(2022, 5, 11, 21, 28, 40, 868, DateTimeKind.Local).AddTicks(2064),
                            EmailAddress = "Jimmy.Hayes@yahoo.com",
                            FirstName = "Jimmy",
                            LastName = "Hayes",
                            Password = "d70cd115ec2fcb207fd7a94e90032530da232b12",
                            PhoneNumber = "615.357.5577 x30361"
                        },
                        new
                        {
                            CustomerID = new Guid("52679878-f629-3086-d672-dd521987cc60"),
                            BirthDate = new DateTime(2007, 6, 18, 2, 59, 34, 47, DateTimeKind.Local).AddTicks(486),
                            EmailAddress = "Juan_Grimes50@hotmail.com",
                            FirstName = "Juan",
                            LastName = "Grimes",
                            Password = "377fbb4eadc9058801cb06febc316aac9d8e6956",
                            PhoneNumber = "377-839-1976 x705"
                        },
                        new
                        {
                            CustomerID = new Guid("3a5df9d9-cb0c-3ea2-a184-bf49c2157d53"),
                            BirthDate = new DateTime(2016, 9, 10, 14, 47, 0, 798, DateTimeKind.Local).AddTicks(7373),
                            EmailAddress = "Fernando.Franecki@gmail.com",
                            FirstName = "Fernando",
                            LastName = "Franecki",
                            Password = "da71509c0837c4a5560c1f122e0f665450b94559",
                            PhoneNumber = "534.225.5340 x037"
                        },
                        new
                        {
                            CustomerID = new Guid("7b9c6565-7910-ff63-bf75-f0040d8a08a6"),
                            BirthDate = new DateTime(2008, 2, 4, 2, 21, 49, 716, DateTimeKind.Local).AddTicks(8325),
                            EmailAddress = "Samuel_Heathcote@hotmail.com",
                            FirstName = "Samuel",
                            LastName = "Heathcote",
                            Password = "ca6f5476a4cdcaa9d46e88eee89751a26656ae45",
                            PhoneNumber = "498.268.0324 x3402"
                        },
                        new
                        {
                            CustomerID = new Guid("16d8dc6a-df56-eb87-2d85-47810a4bf11e"),
                            BirthDate = new DateTime(2006, 12, 27, 9, 44, 32, 107, DateTimeKind.Local).AddTicks(1502),
                            EmailAddress = "Veronica.Boyer16@yahoo.com",
                            FirstName = "Veronica",
                            LastName = "Boyer",
                            Password = "95e1ec9e98c20021b68202d731aeeaf6ae198e6d",
                            PhoneNumber = "681.213.0386 x0302"
                        },
                        new
                        {
                            CustomerID = new Guid("a9199329-f35a-2f36-41e6-f37f054ec807"),
                            BirthDate = new DateTime(2010, 9, 21, 13, 23, 39, 847, DateTimeKind.Local).AddTicks(9560),
                            EmailAddress = "Penny_Kessler@hotmail.com",
                            FirstName = "Penny",
                            LastName = "Kessler",
                            Password = "e4c4b9d7474fde0170700aeb40d25226cdae7ff4",
                            PhoneNumber = "252.206.8247"
                        },
                        new
                        {
                            CustomerID = new Guid("01b86bb5-6715-e0b4-40ff-f9d2387bb286"),
                            BirthDate = new DateTime(2014, 2, 2, 5, 0, 21, 438, DateTimeKind.Local).AddTicks(2575),
                            EmailAddress = "Kristin_Connelly96@gmail.com",
                            FirstName = "Kristin",
                            LastName = "Connelly",
                            Password = "9503aca712b117af5f31ca2f3614d24d6d738039",
                            PhoneNumber = "1-656-727-5064"
                        },
                        new
                        {
                            CustomerID = new Guid("5136745f-480c-ffec-5d8a-4dff4ce334d2"),
                            BirthDate = new DateTime(2008, 3, 6, 7, 22, 2, 260, DateTimeKind.Local).AddTicks(6079),
                            EmailAddress = "Lamar_Botsford14@yahoo.com",
                            FirstName = "Lamar",
                            LastName = "Botsford",
                            Password = "69a94234008dcda05a0159733478c4824eb215f0",
                            PhoneNumber = "1-432-524-5607"
                        },
                        new
                        {
                            CustomerID = new Guid("d89c3929-883c-c907-e7cf-caae44cc636f"),
                            BirthDate = new DateTime(2008, 11, 11, 13, 12, 5, 332, DateTimeKind.Local).AddTicks(3964),
                            EmailAddress = "Gayle.Bergnaum39@hotmail.com",
                            FirstName = "Gayle",
                            LastName = "Bergnaum",
                            Password = "6be2294785c48cf4c881834b6fc1b98cf51de0e6",
                            PhoneNumber = "810-360-2760 x553"
                        },
                        new
                        {
                            CustomerID = new Guid("6d509eb9-41b3-3d9a-8d91-043e42827cc5"),
                            BirthDate = new DateTime(2021, 2, 11, 17, 25, 13, 681, DateTimeKind.Local).AddTicks(789),
                            EmailAddress = "Nancy_MacGyver@gmail.com",
                            FirstName = "Nancy",
                            LastName = "MacGyver",
                            Password = "b7984651309a47a502ecb94356994926ca99f171",
                            PhoneNumber = "891-964-1521"
                        },
                        new
                        {
                            CustomerID = new Guid("2bb71798-2874-7d0e-7bb4-91108197a9cb"),
                            BirthDate = new DateTime(2012, 7, 10, 5, 11, 27, 611, DateTimeKind.Local).AddTicks(6649),
                            EmailAddress = "Nicole.Botsford86@gmail.com",
                            FirstName = "Nicole",
                            LastName = "Botsford",
                            Password = "49c75605af8053061f3a18e2fffe4aef85d3df63",
                            PhoneNumber = "(233) 721-4706 x8066"
                        },
                        new
                        {
                            CustomerID = new Guid("be554221-800d-9ad8-5223-59ddc35f14c5"),
                            BirthDate = new DateTime(2019, 1, 11, 1, 15, 33, 620, DateTimeKind.Local).AddTicks(3544),
                            EmailAddress = "Rudolph_Hoeger@hotmail.com",
                            FirstName = "Rudolph",
                            LastName = "Hoeger",
                            Password = "f6c5b3d2b99b5403aa0f02a5b79b406186af3982",
                            PhoneNumber = "(548) 522-4428"
                        },
                        new
                        {
                            CustomerID = new Guid("0c031c25-af61-f060-f6d4-f34fd242a3f3"),
                            BirthDate = new DateTime(2016, 12, 20, 9, 8, 22, 837, DateTimeKind.Local).AddTicks(2178),
                            EmailAddress = "Emily_Homenick1@gmail.com",
                            FirstName = "Emily",
                            LastName = "Homenick",
                            Password = "c0d7e2d56a36ac6cfc424deac3694feee002dfd3",
                            PhoneNumber = "1-273-973-4016 x28010"
                        });
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Order", b =>
                {
                    b.Property<Guid>("OrderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BillingName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeliveryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderStatusCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderID");

                    b.HasIndex("AddressId");

                    b.HasIndex("OrderStatusCode");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.OrderedProduct", b =>
                {
                    b.Property<Guid>("OrderedProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OrderedProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderedProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OrderedProductPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderedProductId");

                    b.ToTable("OrderedProduct", (string)null);
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.OrderStatus", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("OrderStatus", (string)null);
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ProductURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("BrandId");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.ProductCategory", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategory");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.ProductImage", b =>
                {
                    b.Property<Guid>("ProductImageID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductImageID");

                    b.ToTable("ProductImage", (string)null);
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Review", b =>
                {
                    b.Property<Guid>("ReviewID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReviewRating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReviewID");

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.ZipCode", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"), 1L, 1);

                    b.Property<string>("Commune")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ZipCodeID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Code");

                    b.ToTable("ZipCode", (string)null);
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Address", b =>
                {
                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("AddressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.ZipCode", "ZipCode")
                        .WithMany("Addresses")
                        .HasForeignKey("ZipCodeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("ZipCode");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Basket", b =>
                {
                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.Customer", "Customer")
                        .WithMany("Baskets")
                        .HasForeignKey("BasketID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.BasketStatus", "BasketStatus")
                        .WithMany("Baskets")
                        .HasForeignKey("BasketStatusCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BasketStatus");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.BasketProduct", b =>
                {
                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.Basket", "Basket")
                        .WithMany("BasketProducts")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.Product", "Product")
                        .WithMany("BasketProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Basket");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Category", b =>
                {
                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Order", b =>
                {
                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.Address", "Address")
                        .WithMany("Orders")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.OrderStatus", "OrderStatus")
                        .WithMany("Orders")
                        .HasForeignKey("OrderStatusCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Customer");

                    b.Navigation("OrderStatus");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.OrderedProduct", b =>
                {
                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.Order", "Order")
                        .WithMany("OrderedProducts")
                        .HasForeignKey("OrderedProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.Product", "Product")
                        .WithMany("OrderedProducts")
                        .HasForeignKey("OrderedProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Product", b =>
                {
                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.ProductCategory", b =>
                {
                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.ProductImage", b =>
                {
                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductImageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Review", b =>
                {
                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.Customer", "Customer")
                        .WithMany("Reviews")
                        .HasForeignKey("ReviewID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BodyRocky.Back.WebApi.DataAccess.Entities.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ReviewID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Address", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Basket", b =>
                {
                    b.Navigation("BasketProducts");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.BasketStatus", b =>
                {
                    b.Navigation("Baskets");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Category", b =>
                {
                    b.Navigation("ProductCategories");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Baskets");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Order", b =>
                {
                    b.Navigation("OrderedProducts");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.OrderStatus", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.Product", b =>
                {
                    b.Navigation("BasketProducts");

                    b.Navigation("OrderedProducts");

                    b.Navigation("ProductCategories");

                    b.Navigation("ProductImages");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("BodyRocky.Back.WebApi.DataAccess.Entities.ZipCode", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
